/* afipServiceSoapProxy.cpp
   Generated by gSOAP 2.8.89 for soap/afip_soap.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "afipServiceSoapProxy.h"

namespace afip {

ServiceSoapProxy::ServiceSoapProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

ServiceSoapProxy::ServiceSoapProxy(const ServiceSoapProxy& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
}

ServiceSoapProxy::ServiceSoapProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	ServiceSoapProxy_init(_soap->imode, _soap->omode);
}

ServiceSoapProxy::ServiceSoapProxy(struct soap *_soap, const char *soap_endpoint_url)
{	this->soap = _soap;
	this->soap_own = false;
	ServiceSoapProxy_init(_soap->imode, _soap->omode);
	soap_endpoint = soap_endpoint_url;
}

ServiceSoapProxy::ServiceSoapProxy(const char *soap_endpoint_url)
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = soap_endpoint_url;
}

ServiceSoapProxy::ServiceSoapProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoapProxy_init(iomode, iomode);
}

ServiceSoapProxy::ServiceSoapProxy(const char *soap_endpoint_url, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoapProxy_init(iomode, iomode);
	soap_endpoint = soap_endpoint_url;
}

ServiceSoapProxy::ServiceSoapProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoapProxy_init(imode, omode);
}

ServiceSoapProxy::~ServiceSoapProxy()
{	if (this->soap_own)
	{	this->destroy();
		soap_free(this->soap);
	}
}

void ServiceSoapProxy::ServiceSoapProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        { "SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL },
        { "SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL },
        { "xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL },
        { "xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL },
        { "ns2", "https://wsaahomo.afip.gov.ar/ws/services/LoginCms", NULL, NULL },
        { "ns1", "http://wsaa.view.sua.dvadac.desein.afip.gov", NULL, NULL },
        { "ns3", "http://ar.gov.afip.dif.FEV1/", NULL, NULL },
        { NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this->soap, namespaces);
}

ServiceSoapProxy *ServiceSoapProxy::copy()
{	ServiceSoapProxy *dup = SOAP_NEW_UNMANAGED(ServiceSoapProxy);
	if (dup)
	{	soap_done(dup->soap);
		soap_copy_context(dup->soap, this->soap);
	}
	return dup;
}

ServiceSoapProxy& ServiceSoapProxy::operator=(const ServiceSoapProxy& rhs)
{	if (this->soap != rhs.soap)
	{	if (this->soap_own)
			soap_free(this->soap);
		this->soap = rhs.soap;
		this->soap_own = false;
		this->soap_endpoint = rhs.soap_endpoint;
	}
	return *this;
}

void ServiceSoapProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void ServiceSoapProxy::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	ServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void ServiceSoapProxy::soap_noheader()
{	this->soap->header = NULL;
}

::SOAP_ENV__Header *ServiceSoapProxy::soap_header()
{	return this->soap->header;
}

::SOAP_ENV__Fault *ServiceSoapProxy::soap_fault()
{	return this->soap->fault;
}

const char *ServiceSoapProxy::soap_fault_subcode()
{	return ::soap_fault_subcode(this->soap);
}

const char *ServiceSoapProxy::soap_fault_string()
{	return ::soap_fault_string(this->soap);
}

const char *ServiceSoapProxy::soap_fault_detail()
{	return ::soap_fault_detail(this->soap);
}

int ServiceSoapProxy::soap_close_socket()
{	return ::soap_closesock(this->soap);
}

int ServiceSoapProxy::soap_force_close_socket()
{	return ::soap_force_closesock(this->soap);
}

void ServiceSoapProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void ServiceSoapProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *ServiceSoapProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int ServiceSoapProxy::send_FECAESolicitar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAESolicitar *ns3__FECAESolicitar)
{
	struct __ns3__FECAESolicitar soap_tmp___ns3__FECAESolicitar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAESolicitar";
	soap_tmp___ns3__FECAESolicitar.ns3__FECAESolicitar = ns3__FECAESolicitar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECAESolicitar(soap, &soap_tmp___ns3__FECAESolicitar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECAESolicitar(soap, &soap_tmp___ns3__FECAESolicitar, "-ns3:FECAESolicitar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECAESolicitar(soap, &soap_tmp___ns3__FECAESolicitar, "-ns3:FECAESolicitar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAESolicitar(_ns3__FECAESolicitarResponse &ns3__FECAESolicitarResponse)
{
	ns3__FECAESolicitarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECAESolicitarResponse.soap_get(soap, "ns3:FECAESolicitarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECompTotXRequest(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompTotXRequest *ns3__FECompTotXRequest)
{
	struct __ns3__FECompTotXRequest soap_tmp___ns3__FECompTotXRequest;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECompTotXRequest";
	soap_tmp___ns3__FECompTotXRequest.ns3__FECompTotXRequest = ns3__FECompTotXRequest;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECompTotXRequest(soap, &soap_tmp___ns3__FECompTotXRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECompTotXRequest(soap, &soap_tmp___ns3__FECompTotXRequest, "-ns3:FECompTotXRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECompTotXRequest(soap, &soap_tmp___ns3__FECompTotXRequest, "-ns3:FECompTotXRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECompTotXRequest(_ns3__FECompTotXRequestResponse &ns3__FECompTotXRequestResponse)
{
	ns3__FECompTotXRequestResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECompTotXRequestResponse.soap_get(soap, "ns3:FECompTotXRequestResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEDummy(const char *soap_endpoint_url, const char *soap_action, _ns3__FEDummy *ns3__FEDummy)
{
	struct __ns3__FEDummy soap_tmp___ns3__FEDummy;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEDummy";
	soap_tmp___ns3__FEDummy.ns3__FEDummy = ns3__FEDummy;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEDummy(soap, &soap_tmp___ns3__FEDummy);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEDummy(soap, &soap_tmp___ns3__FEDummy, "-ns3:FEDummy", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEDummy(soap, &soap_tmp___ns3__FEDummy, "-ns3:FEDummy", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEDummy(_ns3__FEDummyResponse &ns3__FEDummyResponse)
{
	ns3__FEDummyResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEDummyResponse.soap_get(soap, "ns3:FEDummyResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECompUltimoAutorizado(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompUltimoAutorizado *ns3__FECompUltimoAutorizado)
{
	struct __ns3__FECompUltimoAutorizado soap_tmp___ns3__FECompUltimoAutorizado;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECompUltimoAutorizado";
	soap_tmp___ns3__FECompUltimoAutorizado.ns3__FECompUltimoAutorizado = ns3__FECompUltimoAutorizado;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECompUltimoAutorizado(soap, &soap_tmp___ns3__FECompUltimoAutorizado);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECompUltimoAutorizado(soap, &soap_tmp___ns3__FECompUltimoAutorizado, "-ns3:FECompUltimoAutorizado", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECompUltimoAutorizado(soap, &soap_tmp___ns3__FECompUltimoAutorizado, "-ns3:FECompUltimoAutorizado", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECompUltimoAutorizado(_ns3__FECompUltimoAutorizadoResponse &ns3__FECompUltimoAutorizadoResponse)
{
	ns3__FECompUltimoAutorizadoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECompUltimoAutorizadoResponse.soap_get(soap, "ns3:FECompUltimoAutorizadoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECompConsultar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompConsultar *ns3__FECompConsultar)
{
	struct __ns3__FECompConsultar soap_tmp___ns3__FECompConsultar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECompConsultar";
	soap_tmp___ns3__FECompConsultar.ns3__FECompConsultar = ns3__FECompConsultar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECompConsultar(soap, &soap_tmp___ns3__FECompConsultar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECompConsultar(soap, &soap_tmp___ns3__FECompConsultar, "-ns3:FECompConsultar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECompConsultar(soap, &soap_tmp___ns3__FECompConsultar, "-ns3:FECompConsultar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECompConsultar(_ns3__FECompConsultarResponse &ns3__FECompConsultarResponse)
{
	ns3__FECompConsultarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECompConsultarResponse.soap_get(soap, "ns3:FECompConsultarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEARegInformativo(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEARegInformativo *ns3__FECAEARegInformativo)
{
	struct __ns3__FECAEARegInformativo soap_tmp___ns3__FECAEARegInformativo;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEARegInformativo";
	soap_tmp___ns3__FECAEARegInformativo.ns3__FECAEARegInformativo = ns3__FECAEARegInformativo;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECAEARegInformativo(soap, &soap_tmp___ns3__FECAEARegInformativo);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECAEARegInformativo(soap, &soap_tmp___ns3__FECAEARegInformativo, "-ns3:FECAEARegInformativo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECAEARegInformativo(soap, &soap_tmp___ns3__FECAEARegInformativo, "-ns3:FECAEARegInformativo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEARegInformativo(_ns3__FECAEARegInformativoResponse &ns3__FECAEARegInformativoResponse)
{
	ns3__FECAEARegInformativoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECAEARegInformativoResponse.soap_get(soap, "ns3:FECAEARegInformativoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEASolicitar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASolicitar *ns3__FECAEASolicitar)
{
	struct __ns3__FECAEASolicitar soap_tmp___ns3__FECAEASolicitar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEASolicitar";
	soap_tmp___ns3__FECAEASolicitar.ns3__FECAEASolicitar = ns3__FECAEASolicitar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECAEASolicitar(soap, &soap_tmp___ns3__FECAEASolicitar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECAEASolicitar(soap, &soap_tmp___ns3__FECAEASolicitar, "-ns3:FECAEASolicitar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECAEASolicitar(soap, &soap_tmp___ns3__FECAEASolicitar, "-ns3:FECAEASolicitar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEASolicitar(_ns3__FECAEASolicitarResponse &ns3__FECAEASolicitarResponse)
{
	ns3__FECAEASolicitarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECAEASolicitarResponse.soap_get(soap, "ns3:FECAEASolicitarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEASinMovimientoConsultar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASinMovimientoConsultar *ns3__FECAEASinMovimientoConsultar)
{
	struct __ns3__FECAEASinMovimientoConsultar soap_tmp___ns3__FECAEASinMovimientoConsultar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoConsultar";
	soap_tmp___ns3__FECAEASinMovimientoConsultar.ns3__FECAEASinMovimientoConsultar = ns3__FECAEASinMovimientoConsultar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECAEASinMovimientoConsultar(soap, &soap_tmp___ns3__FECAEASinMovimientoConsultar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECAEASinMovimientoConsultar(soap, &soap_tmp___ns3__FECAEASinMovimientoConsultar, "-ns3:FECAEASinMovimientoConsultar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECAEASinMovimientoConsultar(soap, &soap_tmp___ns3__FECAEASinMovimientoConsultar, "-ns3:FECAEASinMovimientoConsultar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEASinMovimientoConsultar(_ns3__FECAEASinMovimientoConsultarResponse &ns3__FECAEASinMovimientoConsultarResponse)
{
	ns3__FECAEASinMovimientoConsultarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECAEASinMovimientoConsultarResponse.soap_get(soap, "ns3:FECAEASinMovimientoConsultarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEASinMovimientoInformar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASinMovimientoInformar *ns3__FECAEASinMovimientoInformar)
{
	struct __ns3__FECAEASinMovimientoInformar soap_tmp___ns3__FECAEASinMovimientoInformar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoInformar";
	soap_tmp___ns3__FECAEASinMovimientoInformar.ns3__FECAEASinMovimientoInformar = ns3__FECAEASinMovimientoInformar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECAEASinMovimientoInformar(soap, &soap_tmp___ns3__FECAEASinMovimientoInformar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECAEASinMovimientoInformar(soap, &soap_tmp___ns3__FECAEASinMovimientoInformar, "-ns3:FECAEASinMovimientoInformar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECAEASinMovimientoInformar(soap, &soap_tmp___ns3__FECAEASinMovimientoInformar, "-ns3:FECAEASinMovimientoInformar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEASinMovimientoInformar(_ns3__FECAEASinMovimientoInformarResponse &ns3__FECAEASinMovimientoInformarResponse)
{
	ns3__FECAEASinMovimientoInformarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECAEASinMovimientoInformarResponse.soap_get(soap, "ns3:FECAEASinMovimientoInformarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEAConsultar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEAConsultar *ns3__FECAEAConsultar)
{
	struct __ns3__FECAEAConsultar soap_tmp___ns3__FECAEAConsultar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEAConsultar";
	soap_tmp___ns3__FECAEAConsultar.ns3__FECAEAConsultar = ns3__FECAEAConsultar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECAEAConsultar(soap, &soap_tmp___ns3__FECAEAConsultar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECAEAConsultar(soap, &soap_tmp___ns3__FECAEAConsultar, "-ns3:FECAEAConsultar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECAEAConsultar(soap, &soap_tmp___ns3__FECAEAConsultar, "-ns3:FECAEAConsultar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEAConsultar(_ns3__FECAEAConsultarResponse &ns3__FECAEAConsultarResponse)
{
	ns3__FECAEAConsultarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECAEAConsultarResponse.soap_get(soap, "ns3:FECAEAConsultarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetCotizacion(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetCotizacion *ns3__FEParamGetCotizacion)
{
	struct __ns3__FEParamGetCotizacion soap_tmp___ns3__FEParamGetCotizacion;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetCotizacion";
	soap_tmp___ns3__FEParamGetCotizacion.ns3__FEParamGetCotizacion = ns3__FEParamGetCotizacion;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetCotizacion(soap, &soap_tmp___ns3__FEParamGetCotizacion);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetCotizacion(soap, &soap_tmp___ns3__FEParamGetCotizacion, "-ns3:FEParamGetCotizacion", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetCotizacion(soap, &soap_tmp___ns3__FEParamGetCotizacion, "-ns3:FEParamGetCotizacion", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetCotizacion(_ns3__FEParamGetCotizacionResponse &ns3__FEParamGetCotizacionResponse)
{
	ns3__FEParamGetCotizacionResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetCotizacionResponse.soap_get(soap, "ns3:FEParamGetCotizacionResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposTributos(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposTributos *ns3__FEParamGetTiposTributos)
{
	struct __ns3__FEParamGetTiposTributos soap_tmp___ns3__FEParamGetTiposTributos;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposTributos";
	soap_tmp___ns3__FEParamGetTiposTributos.ns3__FEParamGetTiposTributos = ns3__FEParamGetTiposTributos;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposTributos(soap, &soap_tmp___ns3__FEParamGetTiposTributos);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposTributos(soap, &soap_tmp___ns3__FEParamGetTiposTributos, "-ns3:FEParamGetTiposTributos", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposTributos(soap, &soap_tmp___ns3__FEParamGetTiposTributos, "-ns3:FEParamGetTiposTributos", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposTributos(_ns3__FEParamGetTiposTributosResponse &ns3__FEParamGetTiposTributosResponse)
{
	ns3__FEParamGetTiposTributosResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposTributosResponse.soap_get(soap, "ns3:FEParamGetTiposTributosResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposMonedas(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposMonedas *ns3__FEParamGetTiposMonedas)
{
	struct __ns3__FEParamGetTiposMonedas soap_tmp___ns3__FEParamGetTiposMonedas;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposMonedas";
	soap_tmp___ns3__FEParamGetTiposMonedas.ns3__FEParamGetTiposMonedas = ns3__FEParamGetTiposMonedas;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposMonedas(soap, &soap_tmp___ns3__FEParamGetTiposMonedas);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposMonedas(soap, &soap_tmp___ns3__FEParamGetTiposMonedas, "-ns3:FEParamGetTiposMonedas", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposMonedas(soap, &soap_tmp___ns3__FEParamGetTiposMonedas, "-ns3:FEParamGetTiposMonedas", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposMonedas(_ns3__FEParamGetTiposMonedasResponse &ns3__FEParamGetTiposMonedasResponse)
{
	ns3__FEParamGetTiposMonedasResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposMonedasResponse.soap_get(soap, "ns3:FEParamGetTiposMonedasResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposIva(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposIva *ns3__FEParamGetTiposIva)
{
	struct __ns3__FEParamGetTiposIva soap_tmp___ns3__FEParamGetTiposIva;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposIva";
	soap_tmp___ns3__FEParamGetTiposIva.ns3__FEParamGetTiposIva = ns3__FEParamGetTiposIva;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposIva(soap, &soap_tmp___ns3__FEParamGetTiposIva);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposIva(soap, &soap_tmp___ns3__FEParamGetTiposIva, "-ns3:FEParamGetTiposIva", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposIva(soap, &soap_tmp___ns3__FEParamGetTiposIva, "-ns3:FEParamGetTiposIva", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposIva(_ns3__FEParamGetTiposIvaResponse &ns3__FEParamGetTiposIvaResponse)
{
	ns3__FEParamGetTiposIvaResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposIvaResponse.soap_get(soap, "ns3:FEParamGetTiposIvaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposOpcional(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposOpcional *ns3__FEParamGetTiposOpcional)
{
	struct __ns3__FEParamGetTiposOpcional soap_tmp___ns3__FEParamGetTiposOpcional;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposOpcional";
	soap_tmp___ns3__FEParamGetTiposOpcional.ns3__FEParamGetTiposOpcional = ns3__FEParamGetTiposOpcional;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposOpcional(soap, &soap_tmp___ns3__FEParamGetTiposOpcional);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposOpcional(soap, &soap_tmp___ns3__FEParamGetTiposOpcional, "-ns3:FEParamGetTiposOpcional", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposOpcional(soap, &soap_tmp___ns3__FEParamGetTiposOpcional, "-ns3:FEParamGetTiposOpcional", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposOpcional(_ns3__FEParamGetTiposOpcionalResponse &ns3__FEParamGetTiposOpcionalResponse)
{
	ns3__FEParamGetTiposOpcionalResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposOpcionalResponse.soap_get(soap, "ns3:FEParamGetTiposOpcionalResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposConcepto(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposConcepto *ns3__FEParamGetTiposConcepto)
{
	struct __ns3__FEParamGetTiposConcepto soap_tmp___ns3__FEParamGetTiposConcepto;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposConcepto";
	soap_tmp___ns3__FEParamGetTiposConcepto.ns3__FEParamGetTiposConcepto = ns3__FEParamGetTiposConcepto;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposConcepto(soap, &soap_tmp___ns3__FEParamGetTiposConcepto);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposConcepto(soap, &soap_tmp___ns3__FEParamGetTiposConcepto, "-ns3:FEParamGetTiposConcepto", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposConcepto(soap, &soap_tmp___ns3__FEParamGetTiposConcepto, "-ns3:FEParamGetTiposConcepto", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposConcepto(_ns3__FEParamGetTiposConceptoResponse &ns3__FEParamGetTiposConceptoResponse)
{
	ns3__FEParamGetTiposConceptoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposConceptoResponse.soap_get(soap, "ns3:FEParamGetTiposConceptoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetPtosVenta(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetPtosVenta *ns3__FEParamGetPtosVenta)
{
	struct __ns3__FEParamGetPtosVenta soap_tmp___ns3__FEParamGetPtosVenta;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetPtosVenta";
	soap_tmp___ns3__FEParamGetPtosVenta.ns3__FEParamGetPtosVenta = ns3__FEParamGetPtosVenta;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetPtosVenta(soap, &soap_tmp___ns3__FEParamGetPtosVenta);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetPtosVenta(soap, &soap_tmp___ns3__FEParamGetPtosVenta, "-ns3:FEParamGetPtosVenta", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetPtosVenta(soap, &soap_tmp___ns3__FEParamGetPtosVenta, "-ns3:FEParamGetPtosVenta", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetPtosVenta(_ns3__FEParamGetPtosVentaResponse &ns3__FEParamGetPtosVentaResponse)
{
	ns3__FEParamGetPtosVentaResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetPtosVentaResponse.soap_get(soap, "ns3:FEParamGetPtosVentaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposCbte(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposCbte *ns3__FEParamGetTiposCbte)
{
	struct __ns3__FEParamGetTiposCbte soap_tmp___ns3__FEParamGetTiposCbte;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposCbte";
	soap_tmp___ns3__FEParamGetTiposCbte.ns3__FEParamGetTiposCbte = ns3__FEParamGetTiposCbte;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposCbte(soap, &soap_tmp___ns3__FEParamGetTiposCbte);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposCbte(soap, &soap_tmp___ns3__FEParamGetTiposCbte, "-ns3:FEParamGetTiposCbte", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposCbte(soap, &soap_tmp___ns3__FEParamGetTiposCbte, "-ns3:FEParamGetTiposCbte", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposCbte(_ns3__FEParamGetTiposCbteResponse &ns3__FEParamGetTiposCbteResponse)
{
	ns3__FEParamGetTiposCbteResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposCbteResponse.soap_get(soap, "ns3:FEParamGetTiposCbteResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposDoc(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposDoc *ns3__FEParamGetTiposDoc)
{
	struct __ns3__FEParamGetTiposDoc soap_tmp___ns3__FEParamGetTiposDoc;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposDoc";
	soap_tmp___ns3__FEParamGetTiposDoc.ns3__FEParamGetTiposDoc = ns3__FEParamGetTiposDoc;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposDoc(soap, &soap_tmp___ns3__FEParamGetTiposDoc);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposDoc(soap, &soap_tmp___ns3__FEParamGetTiposDoc, "-ns3:FEParamGetTiposDoc", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposDoc(soap, &soap_tmp___ns3__FEParamGetTiposDoc, "-ns3:FEParamGetTiposDoc", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposDoc(_ns3__FEParamGetTiposDocResponse &ns3__FEParamGetTiposDocResponse)
{
	ns3__FEParamGetTiposDocResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposDocResponse.soap_get(soap, "ns3:FEParamGetTiposDocResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposPaises(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposPaises *ns3__FEParamGetTiposPaises)
{
	struct __ns3__FEParamGetTiposPaises soap_tmp___ns3__FEParamGetTiposPaises;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposPaises";
	soap_tmp___ns3__FEParamGetTiposPaises.ns3__FEParamGetTiposPaises = ns3__FEParamGetTiposPaises;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposPaises(soap, &soap_tmp___ns3__FEParamGetTiposPaises);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposPaises(soap, &soap_tmp___ns3__FEParamGetTiposPaises, "-ns3:FEParamGetTiposPaises", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposPaises(soap, &soap_tmp___ns3__FEParamGetTiposPaises, "-ns3:FEParamGetTiposPaises", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposPaises(_ns3__FEParamGetTiposPaisesResponse &ns3__FEParamGetTiposPaisesResponse)
{
	ns3__FEParamGetTiposPaisesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposPaisesResponse.soap_get(soap, "ns3:FEParamGetTiposPaisesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAESolicitar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAESolicitar *ns3__FECAESolicitar)
{
	struct __ns3__FECAESolicitar_ soap_tmp___ns3__FECAESolicitar_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAESolicitar";
	soap_tmp___ns3__FECAESolicitar_.ns3__FECAESolicitar = ns3__FECAESolicitar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECAESolicitar_(soap, &soap_tmp___ns3__FECAESolicitar_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECAESolicitar_(soap, &soap_tmp___ns3__FECAESolicitar_, "-ns3:FECAESolicitar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECAESolicitar_(soap, &soap_tmp___ns3__FECAESolicitar_, "-ns3:FECAESolicitar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAESolicitar_(_ns3__FECAESolicitarResponse &ns3__FECAESolicitarResponse)
{
	ns3__FECAESolicitarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECAESolicitarResponse.soap_get(soap, "ns3:FECAESolicitarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECompTotXRequest_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompTotXRequest *ns3__FECompTotXRequest)
{
	struct __ns3__FECompTotXRequest_ soap_tmp___ns3__FECompTotXRequest_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECompTotXRequest";
	soap_tmp___ns3__FECompTotXRequest_.ns3__FECompTotXRequest = ns3__FECompTotXRequest;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECompTotXRequest_(soap, &soap_tmp___ns3__FECompTotXRequest_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECompTotXRequest_(soap, &soap_tmp___ns3__FECompTotXRequest_, "-ns3:FECompTotXRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECompTotXRequest_(soap, &soap_tmp___ns3__FECompTotXRequest_, "-ns3:FECompTotXRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECompTotXRequest_(_ns3__FECompTotXRequestResponse &ns3__FECompTotXRequestResponse)
{
	ns3__FECompTotXRequestResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECompTotXRequestResponse.soap_get(soap, "ns3:FECompTotXRequestResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEDummy_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEDummy *ns3__FEDummy)
{
	struct __ns3__FEDummy_ soap_tmp___ns3__FEDummy_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEDummy";
	soap_tmp___ns3__FEDummy_.ns3__FEDummy = ns3__FEDummy;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEDummy_(soap, &soap_tmp___ns3__FEDummy_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEDummy_(soap, &soap_tmp___ns3__FEDummy_, "-ns3:FEDummy", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEDummy_(soap, &soap_tmp___ns3__FEDummy_, "-ns3:FEDummy", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEDummy_(_ns3__FEDummyResponse &ns3__FEDummyResponse)
{
	ns3__FEDummyResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEDummyResponse.soap_get(soap, "ns3:FEDummyResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECompUltimoAutorizado_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompUltimoAutorizado *ns3__FECompUltimoAutorizado)
{
	struct __ns3__FECompUltimoAutorizado_ soap_tmp___ns3__FECompUltimoAutorizado_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECompUltimoAutorizado";
	soap_tmp___ns3__FECompUltimoAutorizado_.ns3__FECompUltimoAutorizado = ns3__FECompUltimoAutorizado;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECompUltimoAutorizado_(soap, &soap_tmp___ns3__FECompUltimoAutorizado_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECompUltimoAutorizado_(soap, &soap_tmp___ns3__FECompUltimoAutorizado_, "-ns3:FECompUltimoAutorizado", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECompUltimoAutorizado_(soap, &soap_tmp___ns3__FECompUltimoAutorizado_, "-ns3:FECompUltimoAutorizado", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECompUltimoAutorizado_(_ns3__FECompUltimoAutorizadoResponse &ns3__FECompUltimoAutorizadoResponse)
{
	ns3__FECompUltimoAutorizadoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECompUltimoAutorizadoResponse.soap_get(soap, "ns3:FECompUltimoAutorizadoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECompConsultar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompConsultar *ns3__FECompConsultar)
{
	struct __ns3__FECompConsultar_ soap_tmp___ns3__FECompConsultar_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECompConsultar";
	soap_tmp___ns3__FECompConsultar_.ns3__FECompConsultar = ns3__FECompConsultar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECompConsultar_(soap, &soap_tmp___ns3__FECompConsultar_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECompConsultar_(soap, &soap_tmp___ns3__FECompConsultar_, "-ns3:FECompConsultar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECompConsultar_(soap, &soap_tmp___ns3__FECompConsultar_, "-ns3:FECompConsultar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECompConsultar_(_ns3__FECompConsultarResponse &ns3__FECompConsultarResponse)
{
	ns3__FECompConsultarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECompConsultarResponse.soap_get(soap, "ns3:FECompConsultarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEARegInformativo_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEARegInformativo *ns3__FECAEARegInformativo)
{
	struct __ns3__FECAEARegInformativo_ soap_tmp___ns3__FECAEARegInformativo_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEARegInformativo";
	soap_tmp___ns3__FECAEARegInformativo_.ns3__FECAEARegInformativo = ns3__FECAEARegInformativo;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECAEARegInformativo_(soap, &soap_tmp___ns3__FECAEARegInformativo_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECAEARegInformativo_(soap, &soap_tmp___ns3__FECAEARegInformativo_, "-ns3:FECAEARegInformativo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECAEARegInformativo_(soap, &soap_tmp___ns3__FECAEARegInformativo_, "-ns3:FECAEARegInformativo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEARegInformativo_(_ns3__FECAEARegInformativoResponse &ns3__FECAEARegInformativoResponse)
{
	ns3__FECAEARegInformativoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECAEARegInformativoResponse.soap_get(soap, "ns3:FECAEARegInformativoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEASolicitar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASolicitar *ns3__FECAEASolicitar)
{
	struct __ns3__FECAEASolicitar_ soap_tmp___ns3__FECAEASolicitar_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEASolicitar";
	soap_tmp___ns3__FECAEASolicitar_.ns3__FECAEASolicitar = ns3__FECAEASolicitar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECAEASolicitar_(soap, &soap_tmp___ns3__FECAEASolicitar_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECAEASolicitar_(soap, &soap_tmp___ns3__FECAEASolicitar_, "-ns3:FECAEASolicitar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECAEASolicitar_(soap, &soap_tmp___ns3__FECAEASolicitar_, "-ns3:FECAEASolicitar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEASolicitar_(_ns3__FECAEASolicitarResponse &ns3__FECAEASolicitarResponse)
{
	ns3__FECAEASolicitarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECAEASolicitarResponse.soap_get(soap, "ns3:FECAEASolicitarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEASinMovimientoConsultar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASinMovimientoConsultar *ns3__FECAEASinMovimientoConsultar)
{
	struct __ns3__FECAEASinMovimientoConsultar_ soap_tmp___ns3__FECAEASinMovimientoConsultar_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoConsultar";
	soap_tmp___ns3__FECAEASinMovimientoConsultar_.ns3__FECAEASinMovimientoConsultar = ns3__FECAEASinMovimientoConsultar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECAEASinMovimientoConsultar_(soap, &soap_tmp___ns3__FECAEASinMovimientoConsultar_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECAEASinMovimientoConsultar_(soap, &soap_tmp___ns3__FECAEASinMovimientoConsultar_, "-ns3:FECAEASinMovimientoConsultar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECAEASinMovimientoConsultar_(soap, &soap_tmp___ns3__FECAEASinMovimientoConsultar_, "-ns3:FECAEASinMovimientoConsultar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEASinMovimientoConsultar_(_ns3__FECAEASinMovimientoConsultarResponse &ns3__FECAEASinMovimientoConsultarResponse)
{
	ns3__FECAEASinMovimientoConsultarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECAEASinMovimientoConsultarResponse.soap_get(soap, "ns3:FECAEASinMovimientoConsultarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEASinMovimientoInformar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASinMovimientoInformar *ns3__FECAEASinMovimientoInformar)
{
	struct __ns3__FECAEASinMovimientoInformar_ soap_tmp___ns3__FECAEASinMovimientoInformar_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoInformar";
	soap_tmp___ns3__FECAEASinMovimientoInformar_.ns3__FECAEASinMovimientoInformar = ns3__FECAEASinMovimientoInformar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECAEASinMovimientoInformar_(soap, &soap_tmp___ns3__FECAEASinMovimientoInformar_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECAEASinMovimientoInformar_(soap, &soap_tmp___ns3__FECAEASinMovimientoInformar_, "-ns3:FECAEASinMovimientoInformar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECAEASinMovimientoInformar_(soap, &soap_tmp___ns3__FECAEASinMovimientoInformar_, "-ns3:FECAEASinMovimientoInformar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEASinMovimientoInformar_(_ns3__FECAEASinMovimientoInformarResponse &ns3__FECAEASinMovimientoInformarResponse)
{
	ns3__FECAEASinMovimientoInformarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECAEASinMovimientoInformarResponse.soap_get(soap, "ns3:FECAEASinMovimientoInformarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEAConsultar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEAConsultar *ns3__FECAEAConsultar)
{
	struct __ns3__FECAEAConsultar_ soap_tmp___ns3__FECAEAConsultar_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEAConsultar";
	soap_tmp___ns3__FECAEAConsultar_.ns3__FECAEAConsultar = ns3__FECAEAConsultar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FECAEAConsultar_(soap, &soap_tmp___ns3__FECAEAConsultar_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FECAEAConsultar_(soap, &soap_tmp___ns3__FECAEAConsultar_, "-ns3:FECAEAConsultar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FECAEAConsultar_(soap, &soap_tmp___ns3__FECAEAConsultar_, "-ns3:FECAEAConsultar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEAConsultar_(_ns3__FECAEAConsultarResponse &ns3__FECAEAConsultarResponse)
{
	ns3__FECAEAConsultarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FECAEAConsultarResponse.soap_get(soap, "ns3:FECAEAConsultarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetCotizacion_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetCotizacion *ns3__FEParamGetCotizacion)
{
	struct __ns3__FEParamGetCotizacion_ soap_tmp___ns3__FEParamGetCotizacion_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetCotizacion";
	soap_tmp___ns3__FEParamGetCotizacion_.ns3__FEParamGetCotizacion = ns3__FEParamGetCotizacion;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetCotizacion_(soap, &soap_tmp___ns3__FEParamGetCotizacion_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetCotizacion_(soap, &soap_tmp___ns3__FEParamGetCotizacion_, "-ns3:FEParamGetCotizacion", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetCotizacion_(soap, &soap_tmp___ns3__FEParamGetCotizacion_, "-ns3:FEParamGetCotizacion", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetCotizacion_(_ns3__FEParamGetCotizacionResponse &ns3__FEParamGetCotizacionResponse)
{
	ns3__FEParamGetCotizacionResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetCotizacionResponse.soap_get(soap, "ns3:FEParamGetCotizacionResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposTributos_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposTributos *ns3__FEParamGetTiposTributos)
{
	struct __ns3__FEParamGetTiposTributos_ soap_tmp___ns3__FEParamGetTiposTributos_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposTributos";
	soap_tmp___ns3__FEParamGetTiposTributos_.ns3__FEParamGetTiposTributos = ns3__FEParamGetTiposTributos;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposTributos_(soap, &soap_tmp___ns3__FEParamGetTiposTributos_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposTributos_(soap, &soap_tmp___ns3__FEParamGetTiposTributos_, "-ns3:FEParamGetTiposTributos", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposTributos_(soap, &soap_tmp___ns3__FEParamGetTiposTributos_, "-ns3:FEParamGetTiposTributos", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposTributos_(_ns3__FEParamGetTiposTributosResponse &ns3__FEParamGetTiposTributosResponse)
{
	ns3__FEParamGetTiposTributosResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposTributosResponse.soap_get(soap, "ns3:FEParamGetTiposTributosResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposMonedas_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposMonedas *ns3__FEParamGetTiposMonedas)
{
	struct __ns3__FEParamGetTiposMonedas_ soap_tmp___ns3__FEParamGetTiposMonedas_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposMonedas";
	soap_tmp___ns3__FEParamGetTiposMonedas_.ns3__FEParamGetTiposMonedas = ns3__FEParamGetTiposMonedas;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposMonedas_(soap, &soap_tmp___ns3__FEParamGetTiposMonedas_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposMonedas_(soap, &soap_tmp___ns3__FEParamGetTiposMonedas_, "-ns3:FEParamGetTiposMonedas", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposMonedas_(soap, &soap_tmp___ns3__FEParamGetTiposMonedas_, "-ns3:FEParamGetTiposMonedas", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposMonedas_(_ns3__FEParamGetTiposMonedasResponse &ns3__FEParamGetTiposMonedasResponse)
{
	ns3__FEParamGetTiposMonedasResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposMonedasResponse.soap_get(soap, "ns3:FEParamGetTiposMonedasResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposIva_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposIva *ns3__FEParamGetTiposIva)
{
	struct __ns3__FEParamGetTiposIva_ soap_tmp___ns3__FEParamGetTiposIva_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposIva";
	soap_tmp___ns3__FEParamGetTiposIva_.ns3__FEParamGetTiposIva = ns3__FEParamGetTiposIva;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposIva_(soap, &soap_tmp___ns3__FEParamGetTiposIva_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposIva_(soap, &soap_tmp___ns3__FEParamGetTiposIva_, "-ns3:FEParamGetTiposIva", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposIva_(soap, &soap_tmp___ns3__FEParamGetTiposIva_, "-ns3:FEParamGetTiposIva", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposIva_(_ns3__FEParamGetTiposIvaResponse &ns3__FEParamGetTiposIvaResponse)
{
	ns3__FEParamGetTiposIvaResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposIvaResponse.soap_get(soap, "ns3:FEParamGetTiposIvaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposOpcional_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposOpcional *ns3__FEParamGetTiposOpcional)
{
	struct __ns3__FEParamGetTiposOpcional_ soap_tmp___ns3__FEParamGetTiposOpcional_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposOpcional";
	soap_tmp___ns3__FEParamGetTiposOpcional_.ns3__FEParamGetTiposOpcional = ns3__FEParamGetTiposOpcional;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposOpcional_(soap, &soap_tmp___ns3__FEParamGetTiposOpcional_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposOpcional_(soap, &soap_tmp___ns3__FEParamGetTiposOpcional_, "-ns3:FEParamGetTiposOpcional", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposOpcional_(soap, &soap_tmp___ns3__FEParamGetTiposOpcional_, "-ns3:FEParamGetTiposOpcional", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposOpcional_(_ns3__FEParamGetTiposOpcionalResponse &ns3__FEParamGetTiposOpcionalResponse)
{
	ns3__FEParamGetTiposOpcionalResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposOpcionalResponse.soap_get(soap, "ns3:FEParamGetTiposOpcionalResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposConcepto_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposConcepto *ns3__FEParamGetTiposConcepto)
{
	struct __ns3__FEParamGetTiposConcepto_ soap_tmp___ns3__FEParamGetTiposConcepto_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposConcepto";
	soap_tmp___ns3__FEParamGetTiposConcepto_.ns3__FEParamGetTiposConcepto = ns3__FEParamGetTiposConcepto;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposConcepto_(soap, &soap_tmp___ns3__FEParamGetTiposConcepto_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposConcepto_(soap, &soap_tmp___ns3__FEParamGetTiposConcepto_, "-ns3:FEParamGetTiposConcepto", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposConcepto_(soap, &soap_tmp___ns3__FEParamGetTiposConcepto_, "-ns3:FEParamGetTiposConcepto", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposConcepto_(_ns3__FEParamGetTiposConceptoResponse &ns3__FEParamGetTiposConceptoResponse)
{
	ns3__FEParamGetTiposConceptoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposConceptoResponse.soap_get(soap, "ns3:FEParamGetTiposConceptoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetPtosVenta_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetPtosVenta *ns3__FEParamGetPtosVenta)
{
	struct __ns3__FEParamGetPtosVenta_ soap_tmp___ns3__FEParamGetPtosVenta_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetPtosVenta";
	soap_tmp___ns3__FEParamGetPtosVenta_.ns3__FEParamGetPtosVenta = ns3__FEParamGetPtosVenta;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetPtosVenta_(soap, &soap_tmp___ns3__FEParamGetPtosVenta_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetPtosVenta_(soap, &soap_tmp___ns3__FEParamGetPtosVenta_, "-ns3:FEParamGetPtosVenta", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetPtosVenta_(soap, &soap_tmp___ns3__FEParamGetPtosVenta_, "-ns3:FEParamGetPtosVenta", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetPtosVenta_(_ns3__FEParamGetPtosVentaResponse &ns3__FEParamGetPtosVentaResponse)
{
	ns3__FEParamGetPtosVentaResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetPtosVentaResponse.soap_get(soap, "ns3:FEParamGetPtosVentaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposCbte_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposCbte *ns3__FEParamGetTiposCbte)
{
	struct __ns3__FEParamGetTiposCbte_ soap_tmp___ns3__FEParamGetTiposCbte_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposCbte";
	soap_tmp___ns3__FEParamGetTiposCbte_.ns3__FEParamGetTiposCbte = ns3__FEParamGetTiposCbte;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposCbte_(soap, &soap_tmp___ns3__FEParamGetTiposCbte_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposCbte_(soap, &soap_tmp___ns3__FEParamGetTiposCbte_, "-ns3:FEParamGetTiposCbte", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposCbte_(soap, &soap_tmp___ns3__FEParamGetTiposCbte_, "-ns3:FEParamGetTiposCbte", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposCbte_(_ns3__FEParamGetTiposCbteResponse &ns3__FEParamGetTiposCbteResponse)
{
	ns3__FEParamGetTiposCbteResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposCbteResponse.soap_get(soap, "ns3:FEParamGetTiposCbteResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposDoc_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposDoc *ns3__FEParamGetTiposDoc)
{
	struct __ns3__FEParamGetTiposDoc_ soap_tmp___ns3__FEParamGetTiposDoc_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposDoc";
	soap_tmp___ns3__FEParamGetTiposDoc_.ns3__FEParamGetTiposDoc = ns3__FEParamGetTiposDoc;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposDoc_(soap, &soap_tmp___ns3__FEParamGetTiposDoc_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposDoc_(soap, &soap_tmp___ns3__FEParamGetTiposDoc_, "-ns3:FEParamGetTiposDoc", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposDoc_(soap, &soap_tmp___ns3__FEParamGetTiposDoc_, "-ns3:FEParamGetTiposDoc", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposDoc_(_ns3__FEParamGetTiposDocResponse &ns3__FEParamGetTiposDocResponse)
{
	ns3__FEParamGetTiposDocResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposDocResponse.soap_get(soap, "ns3:FEParamGetTiposDocResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposPaises_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposPaises *ns3__FEParamGetTiposPaises)
{
	struct __ns3__FEParamGetTiposPaises_ soap_tmp___ns3__FEParamGetTiposPaises_;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposPaises";
	soap_tmp___ns3__FEParamGetTiposPaises_.ns3__FEParamGetTiposPaises = ns3__FEParamGetTiposPaises;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns3__FEParamGetTiposPaises_(soap, &soap_tmp___ns3__FEParamGetTiposPaises_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__FEParamGetTiposPaises_(soap, &soap_tmp___ns3__FEParamGetTiposPaises_, "-ns3:FEParamGetTiposPaises", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__FEParamGetTiposPaises_(soap, &soap_tmp___ns3__FEParamGetTiposPaises_, "-ns3:FEParamGetTiposPaises", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposPaises_(_ns3__FEParamGetTiposPaisesResponse &ns3__FEParamGetTiposPaisesResponse)
{
	ns3__FEParamGetTiposPaisesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__FEParamGetTiposPaisesResponse.soap_get(soap, "ns3:FEParamGetTiposPaisesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

} // namespace afip

/* End of client proxy code */
