/* afipLoginCmsSoapBindingProxy.h
   Generated by gSOAP 2.8.89 for soap/afip_soap.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef afipLoginCmsSoapBindingProxy_H
#define afipLoginCmsSoapBindingProxy_H
#include "afipH.h"

    namespace afip {

    class SOAP_CMAC LoginCmsSoapBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'LoginCmsSoapBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in soap/afip_soap.h, if any
        /// Construct a proxy with new managing context
        LoginCmsSoapBindingProxy();
        /// Copy constructor
        LoginCmsSoapBindingProxy(const LoginCmsSoapBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        LoginCmsSoapBindingProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        LoginCmsSoapBindingProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        LoginCmsSoapBindingProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        LoginCmsSoapBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        LoginCmsSoapBindingProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        LoginCmsSoapBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~LoginCmsSoapBindingProxy();
        /// Initializer used by constructors
        virtual void LoginCmsSoapBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual LoginCmsSoapBindingProxy *copy();
        /// Copy assignment
        LoginCmsSoapBindingProxy& operator=(const LoginCmsSoapBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        // virtual void soap_header(...) method removed due to option -q or -Q
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'loginCms' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int loginCms(_ns1__loginCms *ns1__loginCms, _ns1__loginCmsResponse &ns1__loginCmsResponse) { return this->loginCms(NULL, NULL, ns1__loginCms, ns1__loginCmsResponse); }
        /// Web service synchronous operation 'loginCms' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int loginCms(const char *soap_endpoint_url, const char *soap_action, _ns1__loginCms *ns1__loginCms, _ns1__loginCmsResponse &ns1__loginCmsResponse) { return this->send_loginCms(soap_endpoint_url, soap_action, ns1__loginCms) || this->recv_loginCms(ns1__loginCmsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_loginCms' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_loginCms(const char *soap_endpoint_url, const char *soap_action, _ns1__loginCms *ns1__loginCms);
        /// Web service asynchronous operation 'recv_loginCms' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_loginCms(_ns1__loginCmsResponse &ns1__loginCmsResponse);
    };

    } // namespace afip

#endif
