/* afipServiceSoapProxy.h
   Generated by gSOAP 2.8.89 for soap/afip_soap.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef afipServiceSoapProxy_H
#define afipServiceSoapProxy_H
#include "afipH.h"

    namespace afip {

    class SOAP_CMAC ServiceSoapProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'ServiceSoapProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in soap/afip_soap.h, if any
        /// Construct a proxy with new managing context
        ServiceSoapProxy();
        /// Copy constructor
        ServiceSoapProxy(const ServiceSoapProxy& rhs);
        /// Construct proxy given a shared managing context
        ServiceSoapProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        ServiceSoapProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        ServiceSoapProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        ServiceSoapProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        ServiceSoapProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        ServiceSoapProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~ServiceSoapProxy();
        /// Initializer used by constructors
        virtual void ServiceSoapProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual ServiceSoapProxy *copy();
        /// Copy assignment
        ServiceSoapProxy& operator=(const ServiceSoapProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        // virtual void soap_header(...) method removed due to option -q or -Q
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'FECAESolicitar' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECAESolicitar(_ns3__FECAESolicitar *ns3__FECAESolicitar, _ns3__FECAESolicitarResponse &ns3__FECAESolicitarResponse) { return this->FECAESolicitar(NULL, NULL, ns3__FECAESolicitar, ns3__FECAESolicitarResponse); }
        /// Web service synchronous operation 'FECAESolicitar' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECAESolicitar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAESolicitar *ns3__FECAESolicitar, _ns3__FECAESolicitarResponse &ns3__FECAESolicitarResponse) { return this->send_FECAESolicitar(soap_endpoint_url, soap_action, ns3__FECAESolicitar) || this->recv_FECAESolicitar(ns3__FECAESolicitarResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECAESolicitar' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECAESolicitar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAESolicitar *ns3__FECAESolicitar);
        /// Web service asynchronous operation 'recv_FECAESolicitar' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECAESolicitar(_ns3__FECAESolicitarResponse &ns3__FECAESolicitarResponse);
        //
        /// Web service synchronous operation 'FECompTotXRequest' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECompTotXRequest(_ns3__FECompTotXRequest *ns3__FECompTotXRequest, _ns3__FECompTotXRequestResponse &ns3__FECompTotXRequestResponse) { return this->FECompTotXRequest(NULL, NULL, ns3__FECompTotXRequest, ns3__FECompTotXRequestResponse); }
        /// Web service synchronous operation 'FECompTotXRequest' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECompTotXRequest(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompTotXRequest *ns3__FECompTotXRequest, _ns3__FECompTotXRequestResponse &ns3__FECompTotXRequestResponse) { return this->send_FECompTotXRequest(soap_endpoint_url, soap_action, ns3__FECompTotXRequest) || this->recv_FECompTotXRequest(ns3__FECompTotXRequestResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECompTotXRequest' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECompTotXRequest(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompTotXRequest *ns3__FECompTotXRequest);
        /// Web service asynchronous operation 'recv_FECompTotXRequest' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECompTotXRequest(_ns3__FECompTotXRequestResponse &ns3__FECompTotXRequestResponse);
        //
        /// Web service synchronous operation 'FEDummy' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEDummy(_ns3__FEDummy *ns3__FEDummy, _ns3__FEDummyResponse &ns3__FEDummyResponse) { return this->FEDummy(NULL, NULL, ns3__FEDummy, ns3__FEDummyResponse); }
        /// Web service synchronous operation 'FEDummy' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEDummy(const char *soap_endpoint_url, const char *soap_action, _ns3__FEDummy *ns3__FEDummy, _ns3__FEDummyResponse &ns3__FEDummyResponse) { return this->send_FEDummy(soap_endpoint_url, soap_action, ns3__FEDummy) || this->recv_FEDummy(ns3__FEDummyResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEDummy' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEDummy(const char *soap_endpoint_url, const char *soap_action, _ns3__FEDummy *ns3__FEDummy);
        /// Web service asynchronous operation 'recv_FEDummy' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEDummy(_ns3__FEDummyResponse &ns3__FEDummyResponse);
        //
        /// Web service synchronous operation 'FECompUltimoAutorizado' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECompUltimoAutorizado(_ns3__FECompUltimoAutorizado *ns3__FECompUltimoAutorizado, _ns3__FECompUltimoAutorizadoResponse &ns3__FECompUltimoAutorizadoResponse) { return this->FECompUltimoAutorizado(NULL, NULL, ns3__FECompUltimoAutorizado, ns3__FECompUltimoAutorizadoResponse); }
        /// Web service synchronous operation 'FECompUltimoAutorizado' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECompUltimoAutorizado(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompUltimoAutorizado *ns3__FECompUltimoAutorizado, _ns3__FECompUltimoAutorizadoResponse &ns3__FECompUltimoAutorizadoResponse) { return this->send_FECompUltimoAutorizado(soap_endpoint_url, soap_action, ns3__FECompUltimoAutorizado) || this->recv_FECompUltimoAutorizado(ns3__FECompUltimoAutorizadoResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECompUltimoAutorizado' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECompUltimoAutorizado(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompUltimoAutorizado *ns3__FECompUltimoAutorizado);
        /// Web service asynchronous operation 'recv_FECompUltimoAutorizado' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECompUltimoAutorizado(_ns3__FECompUltimoAutorizadoResponse &ns3__FECompUltimoAutorizadoResponse);
        //
        /// Web service synchronous operation 'FECompConsultar' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECompConsultar(_ns3__FECompConsultar *ns3__FECompConsultar, _ns3__FECompConsultarResponse &ns3__FECompConsultarResponse) { return this->FECompConsultar(NULL, NULL, ns3__FECompConsultar, ns3__FECompConsultarResponse); }
        /// Web service synchronous operation 'FECompConsultar' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECompConsultar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompConsultar *ns3__FECompConsultar, _ns3__FECompConsultarResponse &ns3__FECompConsultarResponse) { return this->send_FECompConsultar(soap_endpoint_url, soap_action, ns3__FECompConsultar) || this->recv_FECompConsultar(ns3__FECompConsultarResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECompConsultar' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECompConsultar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompConsultar *ns3__FECompConsultar);
        /// Web service asynchronous operation 'recv_FECompConsultar' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECompConsultar(_ns3__FECompConsultarResponse &ns3__FECompConsultarResponse);
        //
        /// Web service synchronous operation 'FECAEARegInformativo' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEARegInformativo(_ns3__FECAEARegInformativo *ns3__FECAEARegInformativo, _ns3__FECAEARegInformativoResponse &ns3__FECAEARegInformativoResponse) { return this->FECAEARegInformativo(NULL, NULL, ns3__FECAEARegInformativo, ns3__FECAEARegInformativoResponse); }
        /// Web service synchronous operation 'FECAEARegInformativo' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEARegInformativo(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEARegInformativo *ns3__FECAEARegInformativo, _ns3__FECAEARegInformativoResponse &ns3__FECAEARegInformativoResponse) { return this->send_FECAEARegInformativo(soap_endpoint_url, soap_action, ns3__FECAEARegInformativo) || this->recv_FECAEARegInformativo(ns3__FECAEARegInformativoResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECAEARegInformativo' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECAEARegInformativo(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEARegInformativo *ns3__FECAEARegInformativo);
        /// Web service asynchronous operation 'recv_FECAEARegInformativo' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECAEARegInformativo(_ns3__FECAEARegInformativoResponse &ns3__FECAEARegInformativoResponse);
        //
        /// Web service synchronous operation 'FECAEASolicitar' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEASolicitar(_ns3__FECAEASolicitar *ns3__FECAEASolicitar, _ns3__FECAEASolicitarResponse &ns3__FECAEASolicitarResponse) { return this->FECAEASolicitar(NULL, NULL, ns3__FECAEASolicitar, ns3__FECAEASolicitarResponse); }
        /// Web service synchronous operation 'FECAEASolicitar' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEASolicitar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASolicitar *ns3__FECAEASolicitar, _ns3__FECAEASolicitarResponse &ns3__FECAEASolicitarResponse) { return this->send_FECAEASolicitar(soap_endpoint_url, soap_action, ns3__FECAEASolicitar) || this->recv_FECAEASolicitar(ns3__FECAEASolicitarResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECAEASolicitar' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECAEASolicitar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASolicitar *ns3__FECAEASolicitar);
        /// Web service asynchronous operation 'recv_FECAEASolicitar' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECAEASolicitar(_ns3__FECAEASolicitarResponse &ns3__FECAEASolicitarResponse);
        //
        /// Web service synchronous operation 'FECAEASinMovimientoConsultar' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEASinMovimientoConsultar(_ns3__FECAEASinMovimientoConsultar *ns3__FECAEASinMovimientoConsultar, _ns3__FECAEASinMovimientoConsultarResponse &ns3__FECAEASinMovimientoConsultarResponse) { return this->FECAEASinMovimientoConsultar(NULL, NULL, ns3__FECAEASinMovimientoConsultar, ns3__FECAEASinMovimientoConsultarResponse); }
        /// Web service synchronous operation 'FECAEASinMovimientoConsultar' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEASinMovimientoConsultar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASinMovimientoConsultar *ns3__FECAEASinMovimientoConsultar, _ns3__FECAEASinMovimientoConsultarResponse &ns3__FECAEASinMovimientoConsultarResponse) { return this->send_FECAEASinMovimientoConsultar(soap_endpoint_url, soap_action, ns3__FECAEASinMovimientoConsultar) || this->recv_FECAEASinMovimientoConsultar(ns3__FECAEASinMovimientoConsultarResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECAEASinMovimientoConsultar' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECAEASinMovimientoConsultar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASinMovimientoConsultar *ns3__FECAEASinMovimientoConsultar);
        /// Web service asynchronous operation 'recv_FECAEASinMovimientoConsultar' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECAEASinMovimientoConsultar(_ns3__FECAEASinMovimientoConsultarResponse &ns3__FECAEASinMovimientoConsultarResponse);
        //
        /// Web service synchronous operation 'FECAEASinMovimientoInformar' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEASinMovimientoInformar(_ns3__FECAEASinMovimientoInformar *ns3__FECAEASinMovimientoInformar, _ns3__FECAEASinMovimientoInformarResponse &ns3__FECAEASinMovimientoInformarResponse) { return this->FECAEASinMovimientoInformar(NULL, NULL, ns3__FECAEASinMovimientoInformar, ns3__FECAEASinMovimientoInformarResponse); }
        /// Web service synchronous operation 'FECAEASinMovimientoInformar' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEASinMovimientoInformar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASinMovimientoInformar *ns3__FECAEASinMovimientoInformar, _ns3__FECAEASinMovimientoInformarResponse &ns3__FECAEASinMovimientoInformarResponse) { return this->send_FECAEASinMovimientoInformar(soap_endpoint_url, soap_action, ns3__FECAEASinMovimientoInformar) || this->recv_FECAEASinMovimientoInformar(ns3__FECAEASinMovimientoInformarResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECAEASinMovimientoInformar' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECAEASinMovimientoInformar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASinMovimientoInformar *ns3__FECAEASinMovimientoInformar);
        /// Web service asynchronous operation 'recv_FECAEASinMovimientoInformar' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECAEASinMovimientoInformar(_ns3__FECAEASinMovimientoInformarResponse &ns3__FECAEASinMovimientoInformarResponse);
        //
        /// Web service synchronous operation 'FECAEAConsultar' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEAConsultar(_ns3__FECAEAConsultar *ns3__FECAEAConsultar, _ns3__FECAEAConsultarResponse &ns3__FECAEAConsultarResponse) { return this->FECAEAConsultar(NULL, NULL, ns3__FECAEAConsultar, ns3__FECAEAConsultarResponse); }
        /// Web service synchronous operation 'FECAEAConsultar' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEAConsultar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEAConsultar *ns3__FECAEAConsultar, _ns3__FECAEAConsultarResponse &ns3__FECAEAConsultarResponse) { return this->send_FECAEAConsultar(soap_endpoint_url, soap_action, ns3__FECAEAConsultar) || this->recv_FECAEAConsultar(ns3__FECAEAConsultarResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECAEAConsultar' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECAEAConsultar(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEAConsultar *ns3__FECAEAConsultar);
        /// Web service asynchronous operation 'recv_FECAEAConsultar' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECAEAConsultar(_ns3__FECAEAConsultarResponse &ns3__FECAEAConsultarResponse);
        //
        /// Web service synchronous operation 'FEParamGetCotizacion' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetCotizacion(_ns3__FEParamGetCotizacion *ns3__FEParamGetCotizacion, _ns3__FEParamGetCotizacionResponse &ns3__FEParamGetCotizacionResponse) { return this->FEParamGetCotizacion(NULL, NULL, ns3__FEParamGetCotizacion, ns3__FEParamGetCotizacionResponse); }
        /// Web service synchronous operation 'FEParamGetCotizacion' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetCotizacion(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetCotizacion *ns3__FEParamGetCotizacion, _ns3__FEParamGetCotizacionResponse &ns3__FEParamGetCotizacionResponse) { return this->send_FEParamGetCotizacion(soap_endpoint_url, soap_action, ns3__FEParamGetCotizacion) || this->recv_FEParamGetCotizacion(ns3__FEParamGetCotizacionResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetCotizacion' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetCotizacion(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetCotizacion *ns3__FEParamGetCotizacion);
        /// Web service asynchronous operation 'recv_FEParamGetCotizacion' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetCotizacion(_ns3__FEParamGetCotizacionResponse &ns3__FEParamGetCotizacionResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposTributos' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposTributos(_ns3__FEParamGetTiposTributos *ns3__FEParamGetTiposTributos, _ns3__FEParamGetTiposTributosResponse &ns3__FEParamGetTiposTributosResponse) { return this->FEParamGetTiposTributos(NULL, NULL, ns3__FEParamGetTiposTributos, ns3__FEParamGetTiposTributosResponse); }
        /// Web service synchronous operation 'FEParamGetTiposTributos' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposTributos(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposTributos *ns3__FEParamGetTiposTributos, _ns3__FEParamGetTiposTributosResponse &ns3__FEParamGetTiposTributosResponse) { return this->send_FEParamGetTiposTributos(soap_endpoint_url, soap_action, ns3__FEParamGetTiposTributos) || this->recv_FEParamGetTiposTributos(ns3__FEParamGetTiposTributosResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposTributos' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposTributos(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposTributos *ns3__FEParamGetTiposTributos);
        /// Web service asynchronous operation 'recv_FEParamGetTiposTributos' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposTributos(_ns3__FEParamGetTiposTributosResponse &ns3__FEParamGetTiposTributosResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposMonedas' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposMonedas(_ns3__FEParamGetTiposMonedas *ns3__FEParamGetTiposMonedas, _ns3__FEParamGetTiposMonedasResponse &ns3__FEParamGetTiposMonedasResponse) { return this->FEParamGetTiposMonedas(NULL, NULL, ns3__FEParamGetTiposMonedas, ns3__FEParamGetTiposMonedasResponse); }
        /// Web service synchronous operation 'FEParamGetTiposMonedas' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposMonedas(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposMonedas *ns3__FEParamGetTiposMonedas, _ns3__FEParamGetTiposMonedasResponse &ns3__FEParamGetTiposMonedasResponse) { return this->send_FEParamGetTiposMonedas(soap_endpoint_url, soap_action, ns3__FEParamGetTiposMonedas) || this->recv_FEParamGetTiposMonedas(ns3__FEParamGetTiposMonedasResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposMonedas' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposMonedas(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposMonedas *ns3__FEParamGetTiposMonedas);
        /// Web service asynchronous operation 'recv_FEParamGetTiposMonedas' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposMonedas(_ns3__FEParamGetTiposMonedasResponse &ns3__FEParamGetTiposMonedasResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposIva' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposIva(_ns3__FEParamGetTiposIva *ns3__FEParamGetTiposIva, _ns3__FEParamGetTiposIvaResponse &ns3__FEParamGetTiposIvaResponse) { return this->FEParamGetTiposIva(NULL, NULL, ns3__FEParamGetTiposIva, ns3__FEParamGetTiposIvaResponse); }
        /// Web service synchronous operation 'FEParamGetTiposIva' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposIva(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposIva *ns3__FEParamGetTiposIva, _ns3__FEParamGetTiposIvaResponse &ns3__FEParamGetTiposIvaResponse) { return this->send_FEParamGetTiposIva(soap_endpoint_url, soap_action, ns3__FEParamGetTiposIva) || this->recv_FEParamGetTiposIva(ns3__FEParamGetTiposIvaResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposIva' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposIva(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposIva *ns3__FEParamGetTiposIva);
        /// Web service asynchronous operation 'recv_FEParamGetTiposIva' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposIva(_ns3__FEParamGetTiposIvaResponse &ns3__FEParamGetTiposIvaResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposOpcional' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposOpcional(_ns3__FEParamGetTiposOpcional *ns3__FEParamGetTiposOpcional, _ns3__FEParamGetTiposOpcionalResponse &ns3__FEParamGetTiposOpcionalResponse) { return this->FEParamGetTiposOpcional(NULL, NULL, ns3__FEParamGetTiposOpcional, ns3__FEParamGetTiposOpcionalResponse); }
        /// Web service synchronous operation 'FEParamGetTiposOpcional' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposOpcional(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposOpcional *ns3__FEParamGetTiposOpcional, _ns3__FEParamGetTiposOpcionalResponse &ns3__FEParamGetTiposOpcionalResponse) { return this->send_FEParamGetTiposOpcional(soap_endpoint_url, soap_action, ns3__FEParamGetTiposOpcional) || this->recv_FEParamGetTiposOpcional(ns3__FEParamGetTiposOpcionalResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposOpcional' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposOpcional(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposOpcional *ns3__FEParamGetTiposOpcional);
        /// Web service asynchronous operation 'recv_FEParamGetTiposOpcional' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposOpcional(_ns3__FEParamGetTiposOpcionalResponse &ns3__FEParamGetTiposOpcionalResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposConcepto' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposConcepto(_ns3__FEParamGetTiposConcepto *ns3__FEParamGetTiposConcepto, _ns3__FEParamGetTiposConceptoResponse &ns3__FEParamGetTiposConceptoResponse) { return this->FEParamGetTiposConcepto(NULL, NULL, ns3__FEParamGetTiposConcepto, ns3__FEParamGetTiposConceptoResponse); }
        /// Web service synchronous operation 'FEParamGetTiposConcepto' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposConcepto(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposConcepto *ns3__FEParamGetTiposConcepto, _ns3__FEParamGetTiposConceptoResponse &ns3__FEParamGetTiposConceptoResponse) { return this->send_FEParamGetTiposConcepto(soap_endpoint_url, soap_action, ns3__FEParamGetTiposConcepto) || this->recv_FEParamGetTiposConcepto(ns3__FEParamGetTiposConceptoResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposConcepto' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposConcepto(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposConcepto *ns3__FEParamGetTiposConcepto);
        /// Web service asynchronous operation 'recv_FEParamGetTiposConcepto' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposConcepto(_ns3__FEParamGetTiposConceptoResponse &ns3__FEParamGetTiposConceptoResponse);
        //
        /// Web service synchronous operation 'FEParamGetPtosVenta' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetPtosVenta(_ns3__FEParamGetPtosVenta *ns3__FEParamGetPtosVenta, _ns3__FEParamGetPtosVentaResponse &ns3__FEParamGetPtosVentaResponse) { return this->FEParamGetPtosVenta(NULL, NULL, ns3__FEParamGetPtosVenta, ns3__FEParamGetPtosVentaResponse); }
        /// Web service synchronous operation 'FEParamGetPtosVenta' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetPtosVenta(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetPtosVenta *ns3__FEParamGetPtosVenta, _ns3__FEParamGetPtosVentaResponse &ns3__FEParamGetPtosVentaResponse) { return this->send_FEParamGetPtosVenta(soap_endpoint_url, soap_action, ns3__FEParamGetPtosVenta) || this->recv_FEParamGetPtosVenta(ns3__FEParamGetPtosVentaResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetPtosVenta' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetPtosVenta(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetPtosVenta *ns3__FEParamGetPtosVenta);
        /// Web service asynchronous operation 'recv_FEParamGetPtosVenta' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetPtosVenta(_ns3__FEParamGetPtosVentaResponse &ns3__FEParamGetPtosVentaResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposCbte' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposCbte(_ns3__FEParamGetTiposCbte *ns3__FEParamGetTiposCbte, _ns3__FEParamGetTiposCbteResponse &ns3__FEParamGetTiposCbteResponse) { return this->FEParamGetTiposCbte(NULL, NULL, ns3__FEParamGetTiposCbte, ns3__FEParamGetTiposCbteResponse); }
        /// Web service synchronous operation 'FEParamGetTiposCbte' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposCbte(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposCbte *ns3__FEParamGetTiposCbte, _ns3__FEParamGetTiposCbteResponse &ns3__FEParamGetTiposCbteResponse) { return this->send_FEParamGetTiposCbte(soap_endpoint_url, soap_action, ns3__FEParamGetTiposCbte) || this->recv_FEParamGetTiposCbte(ns3__FEParamGetTiposCbteResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposCbte' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposCbte(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposCbte *ns3__FEParamGetTiposCbte);
        /// Web service asynchronous operation 'recv_FEParamGetTiposCbte' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposCbte(_ns3__FEParamGetTiposCbteResponse &ns3__FEParamGetTiposCbteResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposDoc' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposDoc(_ns3__FEParamGetTiposDoc *ns3__FEParamGetTiposDoc, _ns3__FEParamGetTiposDocResponse &ns3__FEParamGetTiposDocResponse) { return this->FEParamGetTiposDoc(NULL, NULL, ns3__FEParamGetTiposDoc, ns3__FEParamGetTiposDocResponse); }
        /// Web service synchronous operation 'FEParamGetTiposDoc' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposDoc(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposDoc *ns3__FEParamGetTiposDoc, _ns3__FEParamGetTiposDocResponse &ns3__FEParamGetTiposDocResponse) { return this->send_FEParamGetTiposDoc(soap_endpoint_url, soap_action, ns3__FEParamGetTiposDoc) || this->recv_FEParamGetTiposDoc(ns3__FEParamGetTiposDocResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposDoc' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposDoc(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposDoc *ns3__FEParamGetTiposDoc);
        /// Web service asynchronous operation 'recv_FEParamGetTiposDoc' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposDoc(_ns3__FEParamGetTiposDocResponse &ns3__FEParamGetTiposDocResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposPaises' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposPaises(_ns3__FEParamGetTiposPaises *ns3__FEParamGetTiposPaises, _ns3__FEParamGetTiposPaisesResponse &ns3__FEParamGetTiposPaisesResponse) { return this->FEParamGetTiposPaises(NULL, NULL, ns3__FEParamGetTiposPaises, ns3__FEParamGetTiposPaisesResponse); }
        /// Web service synchronous operation 'FEParamGetTiposPaises' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposPaises(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposPaises *ns3__FEParamGetTiposPaises, _ns3__FEParamGetTiposPaisesResponse &ns3__FEParamGetTiposPaisesResponse) { return this->send_FEParamGetTiposPaises(soap_endpoint_url, soap_action, ns3__FEParamGetTiposPaises) || this->recv_FEParamGetTiposPaises(ns3__FEParamGetTiposPaisesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposPaises' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposPaises(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposPaises *ns3__FEParamGetTiposPaises);
        /// Web service asynchronous operation 'recv_FEParamGetTiposPaises' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposPaises(_ns3__FEParamGetTiposPaisesResponse &ns3__FEParamGetTiposPaisesResponse);
        //
        /// Web service synchronous operation 'FECAESolicitar' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECAESolicitar_(_ns3__FECAESolicitar *ns3__FECAESolicitar, _ns3__FECAESolicitarResponse &ns3__FECAESolicitarResponse) { return this->FECAESolicitar_(NULL, NULL, ns3__FECAESolicitar, ns3__FECAESolicitarResponse); }
        /// Web service synchronous operation 'FECAESolicitar' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECAESolicitar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAESolicitar *ns3__FECAESolicitar, _ns3__FECAESolicitarResponse &ns3__FECAESolicitarResponse) { return this->send_FECAESolicitar_(soap_endpoint_url, soap_action, ns3__FECAESolicitar) || this->recv_FECAESolicitar_(ns3__FECAESolicitarResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECAESolicitar' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECAESolicitar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAESolicitar *ns3__FECAESolicitar);
        /// Web service asynchronous operation 'recv_FECAESolicitar' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECAESolicitar_(_ns3__FECAESolicitarResponse &ns3__FECAESolicitarResponse);
        //
        /// Web service synchronous operation 'FECompTotXRequest' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECompTotXRequest_(_ns3__FECompTotXRequest *ns3__FECompTotXRequest, _ns3__FECompTotXRequestResponse &ns3__FECompTotXRequestResponse) { return this->FECompTotXRequest_(NULL, NULL, ns3__FECompTotXRequest, ns3__FECompTotXRequestResponse); }
        /// Web service synchronous operation 'FECompTotXRequest' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECompTotXRequest_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompTotXRequest *ns3__FECompTotXRequest, _ns3__FECompTotXRequestResponse &ns3__FECompTotXRequestResponse) { return this->send_FECompTotXRequest_(soap_endpoint_url, soap_action, ns3__FECompTotXRequest) || this->recv_FECompTotXRequest_(ns3__FECompTotXRequestResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECompTotXRequest' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECompTotXRequest_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompTotXRequest *ns3__FECompTotXRequest);
        /// Web service asynchronous operation 'recv_FECompTotXRequest' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECompTotXRequest_(_ns3__FECompTotXRequestResponse &ns3__FECompTotXRequestResponse);
        //
        /// Web service synchronous operation 'FEDummy' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEDummy_(_ns3__FEDummy *ns3__FEDummy, _ns3__FEDummyResponse &ns3__FEDummyResponse) { return this->FEDummy_(NULL, NULL, ns3__FEDummy, ns3__FEDummyResponse); }
        /// Web service synchronous operation 'FEDummy' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEDummy_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEDummy *ns3__FEDummy, _ns3__FEDummyResponse &ns3__FEDummyResponse) { return this->send_FEDummy_(soap_endpoint_url, soap_action, ns3__FEDummy) || this->recv_FEDummy_(ns3__FEDummyResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEDummy' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEDummy_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEDummy *ns3__FEDummy);
        /// Web service asynchronous operation 'recv_FEDummy' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEDummy_(_ns3__FEDummyResponse &ns3__FEDummyResponse);
        //
        /// Web service synchronous operation 'FECompUltimoAutorizado' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECompUltimoAutorizado_(_ns3__FECompUltimoAutorizado *ns3__FECompUltimoAutorizado, _ns3__FECompUltimoAutorizadoResponse &ns3__FECompUltimoAutorizadoResponse) { return this->FECompUltimoAutorizado_(NULL, NULL, ns3__FECompUltimoAutorizado, ns3__FECompUltimoAutorizadoResponse); }
        /// Web service synchronous operation 'FECompUltimoAutorizado' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECompUltimoAutorizado_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompUltimoAutorizado *ns3__FECompUltimoAutorizado, _ns3__FECompUltimoAutorizadoResponse &ns3__FECompUltimoAutorizadoResponse) { return this->send_FECompUltimoAutorizado_(soap_endpoint_url, soap_action, ns3__FECompUltimoAutorizado) || this->recv_FECompUltimoAutorizado_(ns3__FECompUltimoAutorizadoResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECompUltimoAutorizado' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECompUltimoAutorizado_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompUltimoAutorizado *ns3__FECompUltimoAutorizado);
        /// Web service asynchronous operation 'recv_FECompUltimoAutorizado' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECompUltimoAutorizado_(_ns3__FECompUltimoAutorizadoResponse &ns3__FECompUltimoAutorizadoResponse);
        //
        /// Web service synchronous operation 'FECompConsultar' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECompConsultar_(_ns3__FECompConsultar *ns3__FECompConsultar, _ns3__FECompConsultarResponse &ns3__FECompConsultarResponse) { return this->FECompConsultar_(NULL, NULL, ns3__FECompConsultar, ns3__FECompConsultarResponse); }
        /// Web service synchronous operation 'FECompConsultar' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECompConsultar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompConsultar *ns3__FECompConsultar, _ns3__FECompConsultarResponse &ns3__FECompConsultarResponse) { return this->send_FECompConsultar_(soap_endpoint_url, soap_action, ns3__FECompConsultar) || this->recv_FECompConsultar_(ns3__FECompConsultarResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECompConsultar' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECompConsultar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECompConsultar *ns3__FECompConsultar);
        /// Web service asynchronous operation 'recv_FECompConsultar' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECompConsultar_(_ns3__FECompConsultarResponse &ns3__FECompConsultarResponse);
        //
        /// Web service synchronous operation 'FECAEARegInformativo' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEARegInformativo_(_ns3__FECAEARegInformativo *ns3__FECAEARegInformativo, _ns3__FECAEARegInformativoResponse &ns3__FECAEARegInformativoResponse) { return this->FECAEARegInformativo_(NULL, NULL, ns3__FECAEARegInformativo, ns3__FECAEARegInformativoResponse); }
        /// Web service synchronous operation 'FECAEARegInformativo' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEARegInformativo_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEARegInformativo *ns3__FECAEARegInformativo, _ns3__FECAEARegInformativoResponse &ns3__FECAEARegInformativoResponse) { return this->send_FECAEARegInformativo_(soap_endpoint_url, soap_action, ns3__FECAEARegInformativo) || this->recv_FECAEARegInformativo_(ns3__FECAEARegInformativoResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECAEARegInformativo' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECAEARegInformativo_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEARegInformativo *ns3__FECAEARegInformativo);
        /// Web service asynchronous operation 'recv_FECAEARegInformativo' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECAEARegInformativo_(_ns3__FECAEARegInformativoResponse &ns3__FECAEARegInformativoResponse);
        //
        /// Web service synchronous operation 'FECAEASolicitar' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEASolicitar_(_ns3__FECAEASolicitar *ns3__FECAEASolicitar, _ns3__FECAEASolicitarResponse &ns3__FECAEASolicitarResponse) { return this->FECAEASolicitar_(NULL, NULL, ns3__FECAEASolicitar, ns3__FECAEASolicitarResponse); }
        /// Web service synchronous operation 'FECAEASolicitar' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEASolicitar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASolicitar *ns3__FECAEASolicitar, _ns3__FECAEASolicitarResponse &ns3__FECAEASolicitarResponse) { return this->send_FECAEASolicitar_(soap_endpoint_url, soap_action, ns3__FECAEASolicitar) || this->recv_FECAEASolicitar_(ns3__FECAEASolicitarResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECAEASolicitar' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECAEASolicitar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASolicitar *ns3__FECAEASolicitar);
        /// Web service asynchronous operation 'recv_FECAEASolicitar' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECAEASolicitar_(_ns3__FECAEASolicitarResponse &ns3__FECAEASolicitarResponse);
        //
        /// Web service synchronous operation 'FECAEASinMovimientoConsultar' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEASinMovimientoConsultar_(_ns3__FECAEASinMovimientoConsultar *ns3__FECAEASinMovimientoConsultar, _ns3__FECAEASinMovimientoConsultarResponse &ns3__FECAEASinMovimientoConsultarResponse) { return this->FECAEASinMovimientoConsultar_(NULL, NULL, ns3__FECAEASinMovimientoConsultar, ns3__FECAEASinMovimientoConsultarResponse); }
        /// Web service synchronous operation 'FECAEASinMovimientoConsultar' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEASinMovimientoConsultar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASinMovimientoConsultar *ns3__FECAEASinMovimientoConsultar, _ns3__FECAEASinMovimientoConsultarResponse &ns3__FECAEASinMovimientoConsultarResponse) { return this->send_FECAEASinMovimientoConsultar_(soap_endpoint_url, soap_action, ns3__FECAEASinMovimientoConsultar) || this->recv_FECAEASinMovimientoConsultar_(ns3__FECAEASinMovimientoConsultarResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECAEASinMovimientoConsultar' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECAEASinMovimientoConsultar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASinMovimientoConsultar *ns3__FECAEASinMovimientoConsultar);
        /// Web service asynchronous operation 'recv_FECAEASinMovimientoConsultar' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECAEASinMovimientoConsultar_(_ns3__FECAEASinMovimientoConsultarResponse &ns3__FECAEASinMovimientoConsultarResponse);
        //
        /// Web service synchronous operation 'FECAEASinMovimientoInformar' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEASinMovimientoInformar_(_ns3__FECAEASinMovimientoInformar *ns3__FECAEASinMovimientoInformar, _ns3__FECAEASinMovimientoInformarResponse &ns3__FECAEASinMovimientoInformarResponse) { return this->FECAEASinMovimientoInformar_(NULL, NULL, ns3__FECAEASinMovimientoInformar, ns3__FECAEASinMovimientoInformarResponse); }
        /// Web service synchronous operation 'FECAEASinMovimientoInformar' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEASinMovimientoInformar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASinMovimientoInformar *ns3__FECAEASinMovimientoInformar, _ns3__FECAEASinMovimientoInformarResponse &ns3__FECAEASinMovimientoInformarResponse) { return this->send_FECAEASinMovimientoInformar_(soap_endpoint_url, soap_action, ns3__FECAEASinMovimientoInformar) || this->recv_FECAEASinMovimientoInformar_(ns3__FECAEASinMovimientoInformarResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECAEASinMovimientoInformar' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECAEASinMovimientoInformar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEASinMovimientoInformar *ns3__FECAEASinMovimientoInformar);
        /// Web service asynchronous operation 'recv_FECAEASinMovimientoInformar' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECAEASinMovimientoInformar_(_ns3__FECAEASinMovimientoInformarResponse &ns3__FECAEASinMovimientoInformarResponse);
        //
        /// Web service synchronous operation 'FECAEAConsultar' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEAConsultar_(_ns3__FECAEAConsultar *ns3__FECAEAConsultar, _ns3__FECAEAConsultarResponse &ns3__FECAEAConsultarResponse) { return this->FECAEAConsultar_(NULL, NULL, ns3__FECAEAConsultar, ns3__FECAEAConsultarResponse); }
        /// Web service synchronous operation 'FECAEAConsultar' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FECAEAConsultar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEAConsultar *ns3__FECAEAConsultar, _ns3__FECAEAConsultarResponse &ns3__FECAEAConsultarResponse) { return this->send_FECAEAConsultar_(soap_endpoint_url, soap_action, ns3__FECAEAConsultar) || this->recv_FECAEAConsultar_(ns3__FECAEAConsultarResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FECAEAConsultar' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FECAEAConsultar_(const char *soap_endpoint_url, const char *soap_action, _ns3__FECAEAConsultar *ns3__FECAEAConsultar);
        /// Web service asynchronous operation 'recv_FECAEAConsultar' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FECAEAConsultar_(_ns3__FECAEAConsultarResponse &ns3__FECAEAConsultarResponse);
        //
        /// Web service synchronous operation 'FEParamGetCotizacion' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetCotizacion_(_ns3__FEParamGetCotizacion *ns3__FEParamGetCotizacion, _ns3__FEParamGetCotizacionResponse &ns3__FEParamGetCotizacionResponse) { return this->FEParamGetCotizacion_(NULL, NULL, ns3__FEParamGetCotizacion, ns3__FEParamGetCotizacionResponse); }
        /// Web service synchronous operation 'FEParamGetCotizacion' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetCotizacion_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetCotizacion *ns3__FEParamGetCotizacion, _ns3__FEParamGetCotizacionResponse &ns3__FEParamGetCotizacionResponse) { return this->send_FEParamGetCotizacion_(soap_endpoint_url, soap_action, ns3__FEParamGetCotizacion) || this->recv_FEParamGetCotizacion_(ns3__FEParamGetCotizacionResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetCotizacion' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetCotizacion_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetCotizacion *ns3__FEParamGetCotizacion);
        /// Web service asynchronous operation 'recv_FEParamGetCotizacion' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetCotizacion_(_ns3__FEParamGetCotizacionResponse &ns3__FEParamGetCotizacionResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposTributos' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposTributos_(_ns3__FEParamGetTiposTributos *ns3__FEParamGetTiposTributos, _ns3__FEParamGetTiposTributosResponse &ns3__FEParamGetTiposTributosResponse) { return this->FEParamGetTiposTributos_(NULL, NULL, ns3__FEParamGetTiposTributos, ns3__FEParamGetTiposTributosResponse); }
        /// Web service synchronous operation 'FEParamGetTiposTributos' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposTributos_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposTributos *ns3__FEParamGetTiposTributos, _ns3__FEParamGetTiposTributosResponse &ns3__FEParamGetTiposTributosResponse) { return this->send_FEParamGetTiposTributos_(soap_endpoint_url, soap_action, ns3__FEParamGetTiposTributos) || this->recv_FEParamGetTiposTributos_(ns3__FEParamGetTiposTributosResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposTributos' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposTributos_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposTributos *ns3__FEParamGetTiposTributos);
        /// Web service asynchronous operation 'recv_FEParamGetTiposTributos' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposTributos_(_ns3__FEParamGetTiposTributosResponse &ns3__FEParamGetTiposTributosResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposMonedas' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposMonedas_(_ns3__FEParamGetTiposMonedas *ns3__FEParamGetTiposMonedas, _ns3__FEParamGetTiposMonedasResponse &ns3__FEParamGetTiposMonedasResponse) { return this->FEParamGetTiposMonedas_(NULL, NULL, ns3__FEParamGetTiposMonedas, ns3__FEParamGetTiposMonedasResponse); }
        /// Web service synchronous operation 'FEParamGetTiposMonedas' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposMonedas_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposMonedas *ns3__FEParamGetTiposMonedas, _ns3__FEParamGetTiposMonedasResponse &ns3__FEParamGetTiposMonedasResponse) { return this->send_FEParamGetTiposMonedas_(soap_endpoint_url, soap_action, ns3__FEParamGetTiposMonedas) || this->recv_FEParamGetTiposMonedas_(ns3__FEParamGetTiposMonedasResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposMonedas' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposMonedas_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposMonedas *ns3__FEParamGetTiposMonedas);
        /// Web service asynchronous operation 'recv_FEParamGetTiposMonedas' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposMonedas_(_ns3__FEParamGetTiposMonedasResponse &ns3__FEParamGetTiposMonedasResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposIva' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposIva_(_ns3__FEParamGetTiposIva *ns3__FEParamGetTiposIva, _ns3__FEParamGetTiposIvaResponse &ns3__FEParamGetTiposIvaResponse) { return this->FEParamGetTiposIva_(NULL, NULL, ns3__FEParamGetTiposIva, ns3__FEParamGetTiposIvaResponse); }
        /// Web service synchronous operation 'FEParamGetTiposIva' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposIva_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposIva *ns3__FEParamGetTiposIva, _ns3__FEParamGetTiposIvaResponse &ns3__FEParamGetTiposIvaResponse) { return this->send_FEParamGetTiposIva_(soap_endpoint_url, soap_action, ns3__FEParamGetTiposIva) || this->recv_FEParamGetTiposIva_(ns3__FEParamGetTiposIvaResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposIva' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposIva_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposIva *ns3__FEParamGetTiposIva);
        /// Web service asynchronous operation 'recv_FEParamGetTiposIva' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposIva_(_ns3__FEParamGetTiposIvaResponse &ns3__FEParamGetTiposIvaResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposOpcional' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposOpcional_(_ns3__FEParamGetTiposOpcional *ns3__FEParamGetTiposOpcional, _ns3__FEParamGetTiposOpcionalResponse &ns3__FEParamGetTiposOpcionalResponse) { return this->FEParamGetTiposOpcional_(NULL, NULL, ns3__FEParamGetTiposOpcional, ns3__FEParamGetTiposOpcionalResponse); }
        /// Web service synchronous operation 'FEParamGetTiposOpcional' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposOpcional_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposOpcional *ns3__FEParamGetTiposOpcional, _ns3__FEParamGetTiposOpcionalResponse &ns3__FEParamGetTiposOpcionalResponse) { return this->send_FEParamGetTiposOpcional_(soap_endpoint_url, soap_action, ns3__FEParamGetTiposOpcional) || this->recv_FEParamGetTiposOpcional_(ns3__FEParamGetTiposOpcionalResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposOpcional' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposOpcional_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposOpcional *ns3__FEParamGetTiposOpcional);
        /// Web service asynchronous operation 'recv_FEParamGetTiposOpcional' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposOpcional_(_ns3__FEParamGetTiposOpcionalResponse &ns3__FEParamGetTiposOpcionalResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposConcepto' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposConcepto_(_ns3__FEParamGetTiposConcepto *ns3__FEParamGetTiposConcepto, _ns3__FEParamGetTiposConceptoResponse &ns3__FEParamGetTiposConceptoResponse) { return this->FEParamGetTiposConcepto_(NULL, NULL, ns3__FEParamGetTiposConcepto, ns3__FEParamGetTiposConceptoResponse); }
        /// Web service synchronous operation 'FEParamGetTiposConcepto' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposConcepto_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposConcepto *ns3__FEParamGetTiposConcepto, _ns3__FEParamGetTiposConceptoResponse &ns3__FEParamGetTiposConceptoResponse) { return this->send_FEParamGetTiposConcepto_(soap_endpoint_url, soap_action, ns3__FEParamGetTiposConcepto) || this->recv_FEParamGetTiposConcepto_(ns3__FEParamGetTiposConceptoResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposConcepto' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposConcepto_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposConcepto *ns3__FEParamGetTiposConcepto);
        /// Web service asynchronous operation 'recv_FEParamGetTiposConcepto' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposConcepto_(_ns3__FEParamGetTiposConceptoResponse &ns3__FEParamGetTiposConceptoResponse);
        //
        /// Web service synchronous operation 'FEParamGetPtosVenta' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetPtosVenta_(_ns3__FEParamGetPtosVenta *ns3__FEParamGetPtosVenta, _ns3__FEParamGetPtosVentaResponse &ns3__FEParamGetPtosVentaResponse) { return this->FEParamGetPtosVenta_(NULL, NULL, ns3__FEParamGetPtosVenta, ns3__FEParamGetPtosVentaResponse); }
        /// Web service synchronous operation 'FEParamGetPtosVenta' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetPtosVenta_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetPtosVenta *ns3__FEParamGetPtosVenta, _ns3__FEParamGetPtosVentaResponse &ns3__FEParamGetPtosVentaResponse) { return this->send_FEParamGetPtosVenta_(soap_endpoint_url, soap_action, ns3__FEParamGetPtosVenta) || this->recv_FEParamGetPtosVenta_(ns3__FEParamGetPtosVentaResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetPtosVenta' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetPtosVenta_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetPtosVenta *ns3__FEParamGetPtosVenta);
        /// Web service asynchronous operation 'recv_FEParamGetPtosVenta' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetPtosVenta_(_ns3__FEParamGetPtosVentaResponse &ns3__FEParamGetPtosVentaResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposCbte' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposCbte_(_ns3__FEParamGetTiposCbte *ns3__FEParamGetTiposCbte, _ns3__FEParamGetTiposCbteResponse &ns3__FEParamGetTiposCbteResponse) { return this->FEParamGetTiposCbte_(NULL, NULL, ns3__FEParamGetTiposCbte, ns3__FEParamGetTiposCbteResponse); }
        /// Web service synchronous operation 'FEParamGetTiposCbte' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposCbte_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposCbte *ns3__FEParamGetTiposCbte, _ns3__FEParamGetTiposCbteResponse &ns3__FEParamGetTiposCbteResponse) { return this->send_FEParamGetTiposCbte_(soap_endpoint_url, soap_action, ns3__FEParamGetTiposCbte) || this->recv_FEParamGetTiposCbte_(ns3__FEParamGetTiposCbteResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposCbte' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposCbte_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposCbte *ns3__FEParamGetTiposCbte);
        /// Web service asynchronous operation 'recv_FEParamGetTiposCbte' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposCbte_(_ns3__FEParamGetTiposCbteResponse &ns3__FEParamGetTiposCbteResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposDoc' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposDoc_(_ns3__FEParamGetTiposDoc *ns3__FEParamGetTiposDoc, _ns3__FEParamGetTiposDocResponse &ns3__FEParamGetTiposDocResponse) { return this->FEParamGetTiposDoc_(NULL, NULL, ns3__FEParamGetTiposDoc, ns3__FEParamGetTiposDocResponse); }
        /// Web service synchronous operation 'FEParamGetTiposDoc' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposDoc_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposDoc *ns3__FEParamGetTiposDoc, _ns3__FEParamGetTiposDocResponse &ns3__FEParamGetTiposDocResponse) { return this->send_FEParamGetTiposDoc_(soap_endpoint_url, soap_action, ns3__FEParamGetTiposDoc) || this->recv_FEParamGetTiposDoc_(ns3__FEParamGetTiposDocResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposDoc' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposDoc_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposDoc *ns3__FEParamGetTiposDoc);
        /// Web service asynchronous operation 'recv_FEParamGetTiposDoc' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposDoc_(_ns3__FEParamGetTiposDocResponse &ns3__FEParamGetTiposDocResponse);
        //
        /// Web service synchronous operation 'FEParamGetTiposPaises' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposPaises_(_ns3__FEParamGetTiposPaises *ns3__FEParamGetTiposPaises, _ns3__FEParamGetTiposPaisesResponse &ns3__FEParamGetTiposPaisesResponse) { return this->FEParamGetTiposPaises_(NULL, NULL, ns3__FEParamGetTiposPaises, ns3__FEParamGetTiposPaisesResponse); }
        /// Web service synchronous operation 'FEParamGetTiposPaises' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FEParamGetTiposPaises_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposPaises *ns3__FEParamGetTiposPaises, _ns3__FEParamGetTiposPaisesResponse &ns3__FEParamGetTiposPaisesResponse) { return this->send_FEParamGetTiposPaises_(soap_endpoint_url, soap_action, ns3__FEParamGetTiposPaises) || this->recv_FEParamGetTiposPaises_(ns3__FEParamGetTiposPaisesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FEParamGetTiposPaises' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FEParamGetTiposPaises_(const char *soap_endpoint_url, const char *soap_action, _ns3__FEParamGetTiposPaises *ns3__FEParamGetTiposPaises);
        /// Web service asynchronous operation 'recv_FEParamGetTiposPaises' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FEParamGetTiposPaises_(_ns3__FEParamGetTiposPaisesResponse &ns3__FEParamGetTiposPaisesResponse);
    };

    } // namespace afip

#endif
