/* soapServiceSoap12Proxy.cpp
   Generated by gSOAP 2.8.89 for soap/afip_soap.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapServiceSoap12Proxy.h"

ServiceSoap12Proxy::ServiceSoap12Proxy()
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoap12Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

ServiceSoap12Proxy::ServiceSoap12Proxy(const ServiceSoap12Proxy& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
}

ServiceSoap12Proxy::ServiceSoap12Proxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	ServiceSoap12Proxy_init(_soap->imode, _soap->omode);
}

ServiceSoap12Proxy::ServiceSoap12Proxy(struct soap *_soap, const char *soap_endpoint_url)
{	this->soap = _soap;
	this->soap_own = false;
	ServiceSoap12Proxy_init(_soap->imode, _soap->omode);
	soap_endpoint = soap_endpoint_url;
}

ServiceSoap12Proxy::ServiceSoap12Proxy(const char *soap_endpoint_url)
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoap12Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = soap_endpoint_url;
}

ServiceSoap12Proxy::ServiceSoap12Proxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoap12Proxy_init(iomode, iomode);
}

ServiceSoap12Proxy::ServiceSoap12Proxy(const char *soap_endpoint_url, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoap12Proxy_init(iomode, iomode);
	soap_endpoint = soap_endpoint_url;
}

ServiceSoap12Proxy::ServiceSoap12Proxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoap12Proxy_init(imode, omode);
}

ServiceSoap12Proxy::~ServiceSoap12Proxy()
{	if (this->soap_own)
	{	this->destroy();
		soap_free(this->soap);
	}
}

void ServiceSoap12Proxy::ServiceSoap12Proxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        { "SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL },
        { "SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL },
        { "xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL },
        { "xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL },
        { "afip2", "https://wsaahomo.afip.gov.ar/ws/services/LoginCms", NULL, NULL },
        { "afip1", "http://wsaa.view.sua.dvadac.desein.afip.gov", NULL, NULL },
        { "afip4", "http://ar.gov.afip.dif.FEV1/ServiceSoap", NULL, NULL },
        { "afip3", "http://ar.gov.afip.dif.FEV1/", NULL, NULL },
        { "afip5", "http://ar.gov.afip.dif.FEV1/ServiceSoap12", NULL, NULL },
        { NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this->soap, namespaces);
}

ServiceSoap12Proxy *ServiceSoap12Proxy::copy()
{	ServiceSoap12Proxy *dup = SOAP_NEW_UNMANAGED(ServiceSoap12Proxy);
	if (dup)
	{	soap_done(dup->soap);
		soap_copy_context(dup->soap, this->soap);
	}
	return dup;
}

ServiceSoap12Proxy& ServiceSoap12Proxy::operator=(const ServiceSoap12Proxy& rhs)
{	if (this->soap != rhs.soap)
	{	if (this->soap_own)
			soap_free(this->soap);
		this->soap = rhs.soap;
		this->soap_own = false;
		this->soap_endpoint = rhs.soap_endpoint;
	}
	return *this;
}

void ServiceSoap12Proxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void ServiceSoap12Proxy::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	ServiceSoap12Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void ServiceSoap12Proxy::soap_noheader()
{	this->soap->header = NULL;
}

::SOAP_ENV__Header *ServiceSoap12Proxy::soap_header()
{	return this->soap->header;
}

::SOAP_ENV__Fault *ServiceSoap12Proxy::soap_fault()
{	return this->soap->fault;
}

const char *ServiceSoap12Proxy::soap_fault_subcode()
{	return ::soap_fault_subcode(this->soap);
}

const char *ServiceSoap12Proxy::soap_fault_string()
{	return ::soap_fault_string(this->soap);
}

const char *ServiceSoap12Proxy::soap_fault_detail()
{	return ::soap_fault_detail(this->soap);
}

int ServiceSoap12Proxy::soap_close_socket()
{	return ::soap_closesock(this->soap);
}

int ServiceSoap12Proxy::soap_force_close_socket()
{	return ::soap_force_closesock(this->soap);
}

void ServiceSoap12Proxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void ServiceSoap12Proxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *ServiceSoap12Proxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int ServiceSoap12Proxy::send_FECAESolicitar(const char *soap_endpoint_url, const char *soap_action, _afip3__FECAESolicitar *afip3__FECAESolicitar)
{
	struct __afip5__FECAESolicitar soap_tmp___afip5__FECAESolicitar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAESolicitar";
	soap_tmp___afip5__FECAESolicitar.afip3__FECAESolicitar = afip3__FECAESolicitar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FECAESolicitar(soap, &soap_tmp___afip5__FECAESolicitar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FECAESolicitar(soap, &soap_tmp___afip5__FECAESolicitar, "-afip5:FECAESolicitar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FECAESolicitar(soap, &soap_tmp___afip5__FECAESolicitar, "-afip5:FECAESolicitar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FECAESolicitar(_afip3__FECAESolicitarResponse &afip3__FECAESolicitarResponse)
{
	afip3__FECAESolicitarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECAESolicitarResponse.soap_get(soap, "afip3:FECAESolicitarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FECompTotXRequest(const char *soap_endpoint_url, const char *soap_action, _afip3__FECompTotXRequest *afip3__FECompTotXRequest)
{
	struct __afip5__FECompTotXRequest soap_tmp___afip5__FECompTotXRequest;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECompTotXRequest";
	soap_tmp___afip5__FECompTotXRequest.afip3__FECompTotXRequest = afip3__FECompTotXRequest;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FECompTotXRequest(soap, &soap_tmp___afip5__FECompTotXRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FECompTotXRequest(soap, &soap_tmp___afip5__FECompTotXRequest, "-afip5:FECompTotXRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FECompTotXRequest(soap, &soap_tmp___afip5__FECompTotXRequest, "-afip5:FECompTotXRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FECompTotXRequest(_afip3__FECompTotXRequestResponse &afip3__FECompTotXRequestResponse)
{
	afip3__FECompTotXRequestResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECompTotXRequestResponse.soap_get(soap, "afip3:FECompTotXRequestResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FEDummy(const char *soap_endpoint_url, const char *soap_action, _afip3__FEDummy *afip3__FEDummy)
{
	struct __afip5__FEDummy soap_tmp___afip5__FEDummy;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEDummy";
	soap_tmp___afip5__FEDummy.afip3__FEDummy = afip3__FEDummy;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FEDummy(soap, &soap_tmp___afip5__FEDummy);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FEDummy(soap, &soap_tmp___afip5__FEDummy, "-afip5:FEDummy", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FEDummy(soap, &soap_tmp___afip5__FEDummy, "-afip5:FEDummy", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FEDummy(_afip3__FEDummyResponse &afip3__FEDummyResponse)
{
	afip3__FEDummyResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEDummyResponse.soap_get(soap, "afip3:FEDummyResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FECompUltimoAutorizado(const char *soap_endpoint_url, const char *soap_action, _afip3__FECompUltimoAutorizado *afip3__FECompUltimoAutorizado)
{
	struct __afip5__FECompUltimoAutorizado soap_tmp___afip5__FECompUltimoAutorizado;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECompUltimoAutorizado";
	soap_tmp___afip5__FECompUltimoAutorizado.afip3__FECompUltimoAutorizado = afip3__FECompUltimoAutorizado;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FECompUltimoAutorizado(soap, &soap_tmp___afip5__FECompUltimoAutorizado);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FECompUltimoAutorizado(soap, &soap_tmp___afip5__FECompUltimoAutorizado, "-afip5:FECompUltimoAutorizado", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FECompUltimoAutorizado(soap, &soap_tmp___afip5__FECompUltimoAutorizado, "-afip5:FECompUltimoAutorizado", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FECompUltimoAutorizado(_afip3__FECompUltimoAutorizadoResponse &afip3__FECompUltimoAutorizadoResponse)
{
	afip3__FECompUltimoAutorizadoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECompUltimoAutorizadoResponse.soap_get(soap, "afip3:FECompUltimoAutorizadoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FECompConsultar(const char *soap_endpoint_url, const char *soap_action, _afip3__FECompConsultar *afip3__FECompConsultar)
{
	struct __afip5__FECompConsultar soap_tmp___afip5__FECompConsultar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECompConsultar";
	soap_tmp___afip5__FECompConsultar.afip3__FECompConsultar = afip3__FECompConsultar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FECompConsultar(soap, &soap_tmp___afip5__FECompConsultar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FECompConsultar(soap, &soap_tmp___afip5__FECompConsultar, "-afip5:FECompConsultar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FECompConsultar(soap, &soap_tmp___afip5__FECompConsultar, "-afip5:FECompConsultar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FECompConsultar(_afip3__FECompConsultarResponse &afip3__FECompConsultarResponse)
{
	afip3__FECompConsultarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECompConsultarResponse.soap_get(soap, "afip3:FECompConsultarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FECAEARegInformativo(const char *soap_endpoint_url, const char *soap_action, _afip3__FECAEARegInformativo *afip3__FECAEARegInformativo)
{
	struct __afip5__FECAEARegInformativo soap_tmp___afip5__FECAEARegInformativo;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEARegInformativo";
	soap_tmp___afip5__FECAEARegInformativo.afip3__FECAEARegInformativo = afip3__FECAEARegInformativo;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FECAEARegInformativo(soap, &soap_tmp___afip5__FECAEARegInformativo);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FECAEARegInformativo(soap, &soap_tmp___afip5__FECAEARegInformativo, "-afip5:FECAEARegInformativo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FECAEARegInformativo(soap, &soap_tmp___afip5__FECAEARegInformativo, "-afip5:FECAEARegInformativo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FECAEARegInformativo(_afip3__FECAEARegInformativoResponse &afip3__FECAEARegInformativoResponse)
{
	afip3__FECAEARegInformativoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECAEARegInformativoResponse.soap_get(soap, "afip3:FECAEARegInformativoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FECAEASolicitar(const char *soap_endpoint_url, const char *soap_action, _afip3__FECAEASolicitar *afip3__FECAEASolicitar)
{
	struct __afip5__FECAEASolicitar soap_tmp___afip5__FECAEASolicitar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEASolicitar";
	soap_tmp___afip5__FECAEASolicitar.afip3__FECAEASolicitar = afip3__FECAEASolicitar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FECAEASolicitar(soap, &soap_tmp___afip5__FECAEASolicitar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FECAEASolicitar(soap, &soap_tmp___afip5__FECAEASolicitar, "-afip5:FECAEASolicitar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FECAEASolicitar(soap, &soap_tmp___afip5__FECAEASolicitar, "-afip5:FECAEASolicitar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FECAEASolicitar(_afip3__FECAEASolicitarResponse &afip3__FECAEASolicitarResponse)
{
	afip3__FECAEASolicitarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECAEASolicitarResponse.soap_get(soap, "afip3:FECAEASolicitarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FECAEASinMovimientoConsultar(const char *soap_endpoint_url, const char *soap_action, _afip3__FECAEASinMovimientoConsultar *afip3__FECAEASinMovimientoConsultar)
{
	struct __afip5__FECAEASinMovimientoConsultar soap_tmp___afip5__FECAEASinMovimientoConsultar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoConsultar";
	soap_tmp___afip5__FECAEASinMovimientoConsultar.afip3__FECAEASinMovimientoConsultar = afip3__FECAEASinMovimientoConsultar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FECAEASinMovimientoConsultar(soap, &soap_tmp___afip5__FECAEASinMovimientoConsultar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FECAEASinMovimientoConsultar(soap, &soap_tmp___afip5__FECAEASinMovimientoConsultar, "-afip5:FECAEASinMovimientoConsultar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FECAEASinMovimientoConsultar(soap, &soap_tmp___afip5__FECAEASinMovimientoConsultar, "-afip5:FECAEASinMovimientoConsultar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FECAEASinMovimientoConsultar(_afip3__FECAEASinMovimientoConsultarResponse &afip3__FECAEASinMovimientoConsultarResponse)
{
	afip3__FECAEASinMovimientoConsultarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECAEASinMovimientoConsultarResponse.soap_get(soap, "afip3:FECAEASinMovimientoConsultarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FECAEASinMovimientoInformar(const char *soap_endpoint_url, const char *soap_action, _afip3__FECAEASinMovimientoInformar *afip3__FECAEASinMovimientoInformar)
{
	struct __afip5__FECAEASinMovimientoInformar soap_tmp___afip5__FECAEASinMovimientoInformar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoInformar";
	soap_tmp___afip5__FECAEASinMovimientoInformar.afip3__FECAEASinMovimientoInformar = afip3__FECAEASinMovimientoInformar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FECAEASinMovimientoInformar(soap, &soap_tmp___afip5__FECAEASinMovimientoInformar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FECAEASinMovimientoInformar(soap, &soap_tmp___afip5__FECAEASinMovimientoInformar, "-afip5:FECAEASinMovimientoInformar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FECAEASinMovimientoInformar(soap, &soap_tmp___afip5__FECAEASinMovimientoInformar, "-afip5:FECAEASinMovimientoInformar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FECAEASinMovimientoInformar(_afip3__FECAEASinMovimientoInformarResponse &afip3__FECAEASinMovimientoInformarResponse)
{
	afip3__FECAEASinMovimientoInformarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECAEASinMovimientoInformarResponse.soap_get(soap, "afip3:FECAEASinMovimientoInformarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FECAEAConsultar(const char *soap_endpoint_url, const char *soap_action, _afip3__FECAEAConsultar *afip3__FECAEAConsultar)
{
	struct __afip5__FECAEAConsultar soap_tmp___afip5__FECAEAConsultar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEAConsultar";
	soap_tmp___afip5__FECAEAConsultar.afip3__FECAEAConsultar = afip3__FECAEAConsultar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FECAEAConsultar(soap, &soap_tmp___afip5__FECAEAConsultar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FECAEAConsultar(soap, &soap_tmp___afip5__FECAEAConsultar, "-afip5:FECAEAConsultar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FECAEAConsultar(soap, &soap_tmp___afip5__FECAEAConsultar, "-afip5:FECAEAConsultar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FECAEAConsultar(_afip3__FECAEAConsultarResponse &afip3__FECAEAConsultarResponse)
{
	afip3__FECAEAConsultarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECAEAConsultarResponse.soap_get(soap, "afip3:FECAEAConsultarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FEParamGetCotizacion(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetCotizacion *afip3__FEParamGetCotizacion)
{
	struct __afip5__FEParamGetCotizacion soap_tmp___afip5__FEParamGetCotizacion;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetCotizacion";
	soap_tmp___afip5__FEParamGetCotizacion.afip3__FEParamGetCotizacion = afip3__FEParamGetCotizacion;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FEParamGetCotizacion(soap, &soap_tmp___afip5__FEParamGetCotizacion);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FEParamGetCotizacion(soap, &soap_tmp___afip5__FEParamGetCotizacion, "-afip5:FEParamGetCotizacion", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FEParamGetCotizacion(soap, &soap_tmp___afip5__FEParamGetCotizacion, "-afip5:FEParamGetCotizacion", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FEParamGetCotizacion(_afip3__FEParamGetCotizacionResponse &afip3__FEParamGetCotizacionResponse)
{
	afip3__FEParamGetCotizacionResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetCotizacionResponse.soap_get(soap, "afip3:FEParamGetCotizacionResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FEParamGetTiposTributos(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposTributos *afip3__FEParamGetTiposTributos)
{
	struct __afip5__FEParamGetTiposTributos soap_tmp___afip5__FEParamGetTiposTributos;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposTributos";
	soap_tmp___afip5__FEParamGetTiposTributos.afip3__FEParamGetTiposTributos = afip3__FEParamGetTiposTributos;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FEParamGetTiposTributos(soap, &soap_tmp___afip5__FEParamGetTiposTributos);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FEParamGetTiposTributos(soap, &soap_tmp___afip5__FEParamGetTiposTributos, "-afip5:FEParamGetTiposTributos", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FEParamGetTiposTributos(soap, &soap_tmp___afip5__FEParamGetTiposTributos, "-afip5:FEParamGetTiposTributos", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FEParamGetTiposTributos(_afip3__FEParamGetTiposTributosResponse &afip3__FEParamGetTiposTributosResponse)
{
	afip3__FEParamGetTiposTributosResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposTributosResponse.soap_get(soap, "afip3:FEParamGetTiposTributosResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FEParamGetTiposMonedas(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposMonedas *afip3__FEParamGetTiposMonedas)
{
	struct __afip5__FEParamGetTiposMonedas soap_tmp___afip5__FEParamGetTiposMonedas;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposMonedas";
	soap_tmp___afip5__FEParamGetTiposMonedas.afip3__FEParamGetTiposMonedas = afip3__FEParamGetTiposMonedas;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FEParamGetTiposMonedas(soap, &soap_tmp___afip5__FEParamGetTiposMonedas);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FEParamGetTiposMonedas(soap, &soap_tmp___afip5__FEParamGetTiposMonedas, "-afip5:FEParamGetTiposMonedas", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FEParamGetTiposMonedas(soap, &soap_tmp___afip5__FEParamGetTiposMonedas, "-afip5:FEParamGetTiposMonedas", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FEParamGetTiposMonedas(_afip3__FEParamGetTiposMonedasResponse &afip3__FEParamGetTiposMonedasResponse)
{
	afip3__FEParamGetTiposMonedasResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposMonedasResponse.soap_get(soap, "afip3:FEParamGetTiposMonedasResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FEParamGetTiposIva(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposIva *afip3__FEParamGetTiposIva)
{
	struct __afip5__FEParamGetTiposIva soap_tmp___afip5__FEParamGetTiposIva;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposIva";
	soap_tmp___afip5__FEParamGetTiposIva.afip3__FEParamGetTiposIva = afip3__FEParamGetTiposIva;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FEParamGetTiposIva(soap, &soap_tmp___afip5__FEParamGetTiposIva);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FEParamGetTiposIva(soap, &soap_tmp___afip5__FEParamGetTiposIva, "-afip5:FEParamGetTiposIva", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FEParamGetTiposIva(soap, &soap_tmp___afip5__FEParamGetTiposIva, "-afip5:FEParamGetTiposIva", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FEParamGetTiposIva(_afip3__FEParamGetTiposIvaResponse &afip3__FEParamGetTiposIvaResponse)
{
	afip3__FEParamGetTiposIvaResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposIvaResponse.soap_get(soap, "afip3:FEParamGetTiposIvaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FEParamGetTiposOpcional(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposOpcional *afip3__FEParamGetTiposOpcional)
{
	struct __afip5__FEParamGetTiposOpcional soap_tmp___afip5__FEParamGetTiposOpcional;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposOpcional";
	soap_tmp___afip5__FEParamGetTiposOpcional.afip3__FEParamGetTiposOpcional = afip3__FEParamGetTiposOpcional;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FEParamGetTiposOpcional(soap, &soap_tmp___afip5__FEParamGetTiposOpcional);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FEParamGetTiposOpcional(soap, &soap_tmp___afip5__FEParamGetTiposOpcional, "-afip5:FEParamGetTiposOpcional", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FEParamGetTiposOpcional(soap, &soap_tmp___afip5__FEParamGetTiposOpcional, "-afip5:FEParamGetTiposOpcional", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FEParamGetTiposOpcional(_afip3__FEParamGetTiposOpcionalResponse &afip3__FEParamGetTiposOpcionalResponse)
{
	afip3__FEParamGetTiposOpcionalResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposOpcionalResponse.soap_get(soap, "afip3:FEParamGetTiposOpcionalResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FEParamGetTiposConcepto(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposConcepto *afip3__FEParamGetTiposConcepto)
{
	struct __afip5__FEParamGetTiposConcepto soap_tmp___afip5__FEParamGetTiposConcepto;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposConcepto";
	soap_tmp___afip5__FEParamGetTiposConcepto.afip3__FEParamGetTiposConcepto = afip3__FEParamGetTiposConcepto;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FEParamGetTiposConcepto(soap, &soap_tmp___afip5__FEParamGetTiposConcepto);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FEParamGetTiposConcepto(soap, &soap_tmp___afip5__FEParamGetTiposConcepto, "-afip5:FEParamGetTiposConcepto", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FEParamGetTiposConcepto(soap, &soap_tmp___afip5__FEParamGetTiposConcepto, "-afip5:FEParamGetTiposConcepto", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FEParamGetTiposConcepto(_afip3__FEParamGetTiposConceptoResponse &afip3__FEParamGetTiposConceptoResponse)
{
	afip3__FEParamGetTiposConceptoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposConceptoResponse.soap_get(soap, "afip3:FEParamGetTiposConceptoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FEParamGetPtosVenta(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetPtosVenta *afip3__FEParamGetPtosVenta)
{
	struct __afip5__FEParamGetPtosVenta soap_tmp___afip5__FEParamGetPtosVenta;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetPtosVenta";
	soap_tmp___afip5__FEParamGetPtosVenta.afip3__FEParamGetPtosVenta = afip3__FEParamGetPtosVenta;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FEParamGetPtosVenta(soap, &soap_tmp___afip5__FEParamGetPtosVenta);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FEParamGetPtosVenta(soap, &soap_tmp___afip5__FEParamGetPtosVenta, "-afip5:FEParamGetPtosVenta", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FEParamGetPtosVenta(soap, &soap_tmp___afip5__FEParamGetPtosVenta, "-afip5:FEParamGetPtosVenta", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FEParamGetPtosVenta(_afip3__FEParamGetPtosVentaResponse &afip3__FEParamGetPtosVentaResponse)
{
	afip3__FEParamGetPtosVentaResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetPtosVentaResponse.soap_get(soap, "afip3:FEParamGetPtosVentaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FEParamGetTiposCbte(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposCbte *afip3__FEParamGetTiposCbte)
{
	struct __afip5__FEParamGetTiposCbte soap_tmp___afip5__FEParamGetTiposCbte;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposCbte";
	soap_tmp___afip5__FEParamGetTiposCbte.afip3__FEParamGetTiposCbte = afip3__FEParamGetTiposCbte;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FEParamGetTiposCbte(soap, &soap_tmp___afip5__FEParamGetTiposCbte);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FEParamGetTiposCbte(soap, &soap_tmp___afip5__FEParamGetTiposCbte, "-afip5:FEParamGetTiposCbte", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FEParamGetTiposCbte(soap, &soap_tmp___afip5__FEParamGetTiposCbte, "-afip5:FEParamGetTiposCbte", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FEParamGetTiposCbte(_afip3__FEParamGetTiposCbteResponse &afip3__FEParamGetTiposCbteResponse)
{
	afip3__FEParamGetTiposCbteResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposCbteResponse.soap_get(soap, "afip3:FEParamGetTiposCbteResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FEParamGetTiposDoc(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposDoc *afip3__FEParamGetTiposDoc)
{
	struct __afip5__FEParamGetTiposDoc soap_tmp___afip5__FEParamGetTiposDoc;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposDoc";
	soap_tmp___afip5__FEParamGetTiposDoc.afip3__FEParamGetTiposDoc = afip3__FEParamGetTiposDoc;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FEParamGetTiposDoc(soap, &soap_tmp___afip5__FEParamGetTiposDoc);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FEParamGetTiposDoc(soap, &soap_tmp___afip5__FEParamGetTiposDoc, "-afip5:FEParamGetTiposDoc", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FEParamGetTiposDoc(soap, &soap_tmp___afip5__FEParamGetTiposDoc, "-afip5:FEParamGetTiposDoc", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FEParamGetTiposDoc(_afip3__FEParamGetTiposDocResponse &afip3__FEParamGetTiposDocResponse)
{
	afip3__FEParamGetTiposDocResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposDocResponse.soap_get(soap, "afip3:FEParamGetTiposDocResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoap12Proxy::send_FEParamGetTiposPaises(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposPaises *afip3__FEParamGetTiposPaises)
{
	struct __afip5__FEParamGetTiposPaises soap_tmp___afip5__FEParamGetTiposPaises;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposPaises";
	soap_tmp___afip5__FEParamGetTiposPaises.afip3__FEParamGetTiposPaises = afip3__FEParamGetTiposPaises;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip5__FEParamGetTiposPaises(soap, &soap_tmp___afip5__FEParamGetTiposPaises);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip5__FEParamGetTiposPaises(soap, &soap_tmp___afip5__FEParamGetTiposPaises, "-afip5:FEParamGetTiposPaises", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip5__FEParamGetTiposPaises(soap, &soap_tmp___afip5__FEParamGetTiposPaises, "-afip5:FEParamGetTiposPaises", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoap12Proxy::recv_FEParamGetTiposPaises(_afip3__FEParamGetTiposPaisesResponse &afip3__FEParamGetTiposPaisesResponse)
{
	afip3__FEParamGetTiposPaisesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposPaisesResponse.soap_get(soap, "afip3:FEParamGetTiposPaisesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
