/* soapServiceSoapProxy.cpp
   Generated by gSOAP 2.8.89 for soap/afip_soap.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapServiceSoapProxy.h"

ServiceSoapProxy::ServiceSoapProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

ServiceSoapProxy::ServiceSoapProxy(const ServiceSoapProxy& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
}

ServiceSoapProxy::ServiceSoapProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	ServiceSoapProxy_init(_soap->imode, _soap->omode);
}

ServiceSoapProxy::ServiceSoapProxy(struct soap *_soap, const char *soap_endpoint_url)
{	this->soap = _soap;
	this->soap_own = false;
	ServiceSoapProxy_init(_soap->imode, _soap->omode);
	soap_endpoint = soap_endpoint_url;
}

ServiceSoapProxy::ServiceSoapProxy(const char *soap_endpoint_url)
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = soap_endpoint_url;
}

ServiceSoapProxy::ServiceSoapProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoapProxy_init(iomode, iomode);
}

ServiceSoapProxy::ServiceSoapProxy(const char *soap_endpoint_url, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoapProxy_init(iomode, iomode);
	soap_endpoint = soap_endpoint_url;
}

ServiceSoapProxy::ServiceSoapProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	ServiceSoapProxy_init(imode, omode);
}

ServiceSoapProxy::~ServiceSoapProxy()
{	if (this->soap_own)
	{	this->destroy();
		soap_free(this->soap);
	}
}

void ServiceSoapProxy::ServiceSoapProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        { "SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL },
        { "SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL },
        { "xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL },
        { "xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL },
        { "afip2", "https://wsaahomo.afip.gov.ar/ws/services/LoginCms", NULL, NULL },
        { "afip1", "http://wsaa.view.sua.dvadac.desein.afip.gov", NULL, NULL },
        { "afip4", "http://ar.gov.afip.dif.FEV1/ServiceSoap", NULL, NULL },
        { "afip3", "http://ar.gov.afip.dif.FEV1/", NULL, NULL },
        { "afip5", "http://ar.gov.afip.dif.FEV1/ServiceSoap12", NULL, NULL },
        { NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this->soap, namespaces);
}

ServiceSoapProxy *ServiceSoapProxy::copy()
{	ServiceSoapProxy *dup = SOAP_NEW_UNMANAGED(ServiceSoapProxy);
	if (dup)
	{	soap_done(dup->soap);
		soap_copy_context(dup->soap, this->soap);
	}
	return dup;
}

ServiceSoapProxy& ServiceSoapProxy::operator=(const ServiceSoapProxy& rhs)
{	if (this->soap != rhs.soap)
	{	if (this->soap_own)
			soap_free(this->soap);
		this->soap = rhs.soap;
		this->soap_own = false;
		this->soap_endpoint = rhs.soap_endpoint;
	}
	return *this;
}

void ServiceSoapProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void ServiceSoapProxy::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	ServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void ServiceSoapProxy::soap_noheader()
{	this->soap->header = NULL;
}

::SOAP_ENV__Header *ServiceSoapProxy::soap_header()
{	return this->soap->header;
}

::SOAP_ENV__Fault *ServiceSoapProxy::soap_fault()
{	return this->soap->fault;
}

const char *ServiceSoapProxy::soap_fault_subcode()
{	return ::soap_fault_subcode(this->soap);
}

const char *ServiceSoapProxy::soap_fault_string()
{	return ::soap_fault_string(this->soap);
}

const char *ServiceSoapProxy::soap_fault_detail()
{	return ::soap_fault_detail(this->soap);
}

int ServiceSoapProxy::soap_close_socket()
{	return ::soap_closesock(this->soap);
}

int ServiceSoapProxy::soap_force_close_socket()
{	return ::soap_force_closesock(this->soap);
}

void ServiceSoapProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void ServiceSoapProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *ServiceSoapProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int ServiceSoapProxy::send_FECAESolicitar(const char *soap_endpoint_url, const char *soap_action, _afip3__FECAESolicitar *afip3__FECAESolicitar)
{
	struct __afip4__FECAESolicitar soap_tmp___afip4__FECAESolicitar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAESolicitar";
	soap_tmp___afip4__FECAESolicitar.afip3__FECAESolicitar = afip3__FECAESolicitar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FECAESolicitar(soap, &soap_tmp___afip4__FECAESolicitar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FECAESolicitar(soap, &soap_tmp___afip4__FECAESolicitar, "-afip4:FECAESolicitar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FECAESolicitar(soap, &soap_tmp___afip4__FECAESolicitar, "-afip4:FECAESolicitar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAESolicitar(_afip3__FECAESolicitarResponse &afip3__FECAESolicitarResponse)
{
	afip3__FECAESolicitarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECAESolicitarResponse.soap_get(soap, "afip3:FECAESolicitarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECompTotXRequest(const char *soap_endpoint_url, const char *soap_action, _afip3__FECompTotXRequest *afip3__FECompTotXRequest)
{
	struct __afip4__FECompTotXRequest soap_tmp___afip4__FECompTotXRequest;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECompTotXRequest";
	soap_tmp___afip4__FECompTotXRequest.afip3__FECompTotXRequest = afip3__FECompTotXRequest;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FECompTotXRequest(soap, &soap_tmp___afip4__FECompTotXRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FECompTotXRequest(soap, &soap_tmp___afip4__FECompTotXRequest, "-afip4:FECompTotXRequest", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FECompTotXRequest(soap, &soap_tmp___afip4__FECompTotXRequest, "-afip4:FECompTotXRequest", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECompTotXRequest(_afip3__FECompTotXRequestResponse &afip3__FECompTotXRequestResponse)
{
	afip3__FECompTotXRequestResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECompTotXRequestResponse.soap_get(soap, "afip3:FECompTotXRequestResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEDummy(const char *soap_endpoint_url, const char *soap_action, _afip3__FEDummy *afip3__FEDummy)
{
	struct __afip4__FEDummy soap_tmp___afip4__FEDummy;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEDummy";
	soap_tmp___afip4__FEDummy.afip3__FEDummy = afip3__FEDummy;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FEDummy(soap, &soap_tmp___afip4__FEDummy);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FEDummy(soap, &soap_tmp___afip4__FEDummy, "-afip4:FEDummy", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FEDummy(soap, &soap_tmp___afip4__FEDummy, "-afip4:FEDummy", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEDummy(_afip3__FEDummyResponse &afip3__FEDummyResponse)
{
	afip3__FEDummyResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEDummyResponse.soap_get(soap, "afip3:FEDummyResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECompUltimoAutorizado(const char *soap_endpoint_url, const char *soap_action, _afip3__FECompUltimoAutorizado *afip3__FECompUltimoAutorizado)
{
	struct __afip4__FECompUltimoAutorizado soap_tmp___afip4__FECompUltimoAutorizado;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECompUltimoAutorizado";
	soap_tmp___afip4__FECompUltimoAutorizado.afip3__FECompUltimoAutorizado = afip3__FECompUltimoAutorizado;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FECompUltimoAutorizado(soap, &soap_tmp___afip4__FECompUltimoAutorizado);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FECompUltimoAutorizado(soap, &soap_tmp___afip4__FECompUltimoAutorizado, "-afip4:FECompUltimoAutorizado", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FECompUltimoAutorizado(soap, &soap_tmp___afip4__FECompUltimoAutorizado, "-afip4:FECompUltimoAutorizado", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECompUltimoAutorizado(_afip3__FECompUltimoAutorizadoResponse &afip3__FECompUltimoAutorizadoResponse)
{
	afip3__FECompUltimoAutorizadoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECompUltimoAutorizadoResponse.soap_get(soap, "afip3:FECompUltimoAutorizadoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECompConsultar(const char *soap_endpoint_url, const char *soap_action, _afip3__FECompConsultar *afip3__FECompConsultar)
{
	struct __afip4__FECompConsultar soap_tmp___afip4__FECompConsultar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECompConsultar";
	soap_tmp___afip4__FECompConsultar.afip3__FECompConsultar = afip3__FECompConsultar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FECompConsultar(soap, &soap_tmp___afip4__FECompConsultar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FECompConsultar(soap, &soap_tmp___afip4__FECompConsultar, "-afip4:FECompConsultar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FECompConsultar(soap, &soap_tmp___afip4__FECompConsultar, "-afip4:FECompConsultar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECompConsultar(_afip3__FECompConsultarResponse &afip3__FECompConsultarResponse)
{
	afip3__FECompConsultarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECompConsultarResponse.soap_get(soap, "afip3:FECompConsultarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEARegInformativo(const char *soap_endpoint_url, const char *soap_action, _afip3__FECAEARegInformativo *afip3__FECAEARegInformativo)
{
	struct __afip4__FECAEARegInformativo soap_tmp___afip4__FECAEARegInformativo;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEARegInformativo";
	soap_tmp___afip4__FECAEARegInformativo.afip3__FECAEARegInformativo = afip3__FECAEARegInformativo;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FECAEARegInformativo(soap, &soap_tmp___afip4__FECAEARegInformativo);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FECAEARegInformativo(soap, &soap_tmp___afip4__FECAEARegInformativo, "-afip4:FECAEARegInformativo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FECAEARegInformativo(soap, &soap_tmp___afip4__FECAEARegInformativo, "-afip4:FECAEARegInformativo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEARegInformativo(_afip3__FECAEARegInformativoResponse &afip3__FECAEARegInformativoResponse)
{
	afip3__FECAEARegInformativoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECAEARegInformativoResponse.soap_get(soap, "afip3:FECAEARegInformativoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEASolicitar(const char *soap_endpoint_url, const char *soap_action, _afip3__FECAEASolicitar *afip3__FECAEASolicitar)
{
	struct __afip4__FECAEASolicitar soap_tmp___afip4__FECAEASolicitar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEASolicitar";
	soap_tmp___afip4__FECAEASolicitar.afip3__FECAEASolicitar = afip3__FECAEASolicitar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FECAEASolicitar(soap, &soap_tmp___afip4__FECAEASolicitar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FECAEASolicitar(soap, &soap_tmp___afip4__FECAEASolicitar, "-afip4:FECAEASolicitar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FECAEASolicitar(soap, &soap_tmp___afip4__FECAEASolicitar, "-afip4:FECAEASolicitar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEASolicitar(_afip3__FECAEASolicitarResponse &afip3__FECAEASolicitarResponse)
{
	afip3__FECAEASolicitarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECAEASolicitarResponse.soap_get(soap, "afip3:FECAEASolicitarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEASinMovimientoConsultar(const char *soap_endpoint_url, const char *soap_action, _afip3__FECAEASinMovimientoConsultar *afip3__FECAEASinMovimientoConsultar)
{
	struct __afip4__FECAEASinMovimientoConsultar soap_tmp___afip4__FECAEASinMovimientoConsultar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoConsultar";
	soap_tmp___afip4__FECAEASinMovimientoConsultar.afip3__FECAEASinMovimientoConsultar = afip3__FECAEASinMovimientoConsultar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FECAEASinMovimientoConsultar(soap, &soap_tmp___afip4__FECAEASinMovimientoConsultar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FECAEASinMovimientoConsultar(soap, &soap_tmp___afip4__FECAEASinMovimientoConsultar, "-afip4:FECAEASinMovimientoConsultar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FECAEASinMovimientoConsultar(soap, &soap_tmp___afip4__FECAEASinMovimientoConsultar, "-afip4:FECAEASinMovimientoConsultar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEASinMovimientoConsultar(_afip3__FECAEASinMovimientoConsultarResponse &afip3__FECAEASinMovimientoConsultarResponse)
{
	afip3__FECAEASinMovimientoConsultarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECAEASinMovimientoConsultarResponse.soap_get(soap, "afip3:FECAEASinMovimientoConsultarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEASinMovimientoInformar(const char *soap_endpoint_url, const char *soap_action, _afip3__FECAEASinMovimientoInformar *afip3__FECAEASinMovimientoInformar)
{
	struct __afip4__FECAEASinMovimientoInformar soap_tmp___afip4__FECAEASinMovimientoInformar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoInformar";
	soap_tmp___afip4__FECAEASinMovimientoInformar.afip3__FECAEASinMovimientoInformar = afip3__FECAEASinMovimientoInformar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FECAEASinMovimientoInformar(soap, &soap_tmp___afip4__FECAEASinMovimientoInformar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FECAEASinMovimientoInformar(soap, &soap_tmp___afip4__FECAEASinMovimientoInformar, "-afip4:FECAEASinMovimientoInformar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FECAEASinMovimientoInformar(soap, &soap_tmp___afip4__FECAEASinMovimientoInformar, "-afip4:FECAEASinMovimientoInformar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEASinMovimientoInformar(_afip3__FECAEASinMovimientoInformarResponse &afip3__FECAEASinMovimientoInformarResponse)
{
	afip3__FECAEASinMovimientoInformarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECAEASinMovimientoInformarResponse.soap_get(soap, "afip3:FECAEASinMovimientoInformarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FECAEAConsultar(const char *soap_endpoint_url, const char *soap_action, _afip3__FECAEAConsultar *afip3__FECAEAConsultar)
{
	struct __afip4__FECAEAConsultar soap_tmp___afip4__FECAEAConsultar;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FECAEAConsultar";
	soap_tmp___afip4__FECAEAConsultar.afip3__FECAEAConsultar = afip3__FECAEAConsultar;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FECAEAConsultar(soap, &soap_tmp___afip4__FECAEAConsultar);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FECAEAConsultar(soap, &soap_tmp___afip4__FECAEAConsultar, "-afip4:FECAEAConsultar", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FECAEAConsultar(soap, &soap_tmp___afip4__FECAEAConsultar, "-afip4:FECAEAConsultar", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FECAEAConsultar(_afip3__FECAEAConsultarResponse &afip3__FECAEAConsultarResponse)
{
	afip3__FECAEAConsultarResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FECAEAConsultarResponse.soap_get(soap, "afip3:FECAEAConsultarResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetCotizacion(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetCotizacion *afip3__FEParamGetCotizacion)
{
	struct __afip4__FEParamGetCotizacion soap_tmp___afip4__FEParamGetCotizacion;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetCotizacion";
	soap_tmp___afip4__FEParamGetCotizacion.afip3__FEParamGetCotizacion = afip3__FEParamGetCotizacion;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FEParamGetCotizacion(soap, &soap_tmp___afip4__FEParamGetCotizacion);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FEParamGetCotizacion(soap, &soap_tmp___afip4__FEParamGetCotizacion, "-afip4:FEParamGetCotizacion", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FEParamGetCotizacion(soap, &soap_tmp___afip4__FEParamGetCotizacion, "-afip4:FEParamGetCotizacion", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetCotizacion(_afip3__FEParamGetCotizacionResponse &afip3__FEParamGetCotizacionResponse)
{
	afip3__FEParamGetCotizacionResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetCotizacionResponse.soap_get(soap, "afip3:FEParamGetCotizacionResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposTributos(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposTributos *afip3__FEParamGetTiposTributos)
{
	struct __afip4__FEParamGetTiposTributos soap_tmp___afip4__FEParamGetTiposTributos;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposTributos";
	soap_tmp___afip4__FEParamGetTiposTributos.afip3__FEParamGetTiposTributos = afip3__FEParamGetTiposTributos;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FEParamGetTiposTributos(soap, &soap_tmp___afip4__FEParamGetTiposTributos);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FEParamGetTiposTributos(soap, &soap_tmp___afip4__FEParamGetTiposTributos, "-afip4:FEParamGetTiposTributos", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FEParamGetTiposTributos(soap, &soap_tmp___afip4__FEParamGetTiposTributos, "-afip4:FEParamGetTiposTributos", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposTributos(_afip3__FEParamGetTiposTributosResponse &afip3__FEParamGetTiposTributosResponse)
{
	afip3__FEParamGetTiposTributosResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposTributosResponse.soap_get(soap, "afip3:FEParamGetTiposTributosResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposMonedas(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposMonedas *afip3__FEParamGetTiposMonedas)
{
	struct __afip4__FEParamGetTiposMonedas soap_tmp___afip4__FEParamGetTiposMonedas;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposMonedas";
	soap_tmp___afip4__FEParamGetTiposMonedas.afip3__FEParamGetTiposMonedas = afip3__FEParamGetTiposMonedas;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FEParamGetTiposMonedas(soap, &soap_tmp___afip4__FEParamGetTiposMonedas);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FEParamGetTiposMonedas(soap, &soap_tmp___afip4__FEParamGetTiposMonedas, "-afip4:FEParamGetTiposMonedas", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FEParamGetTiposMonedas(soap, &soap_tmp___afip4__FEParamGetTiposMonedas, "-afip4:FEParamGetTiposMonedas", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposMonedas(_afip3__FEParamGetTiposMonedasResponse &afip3__FEParamGetTiposMonedasResponse)
{
	afip3__FEParamGetTiposMonedasResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposMonedasResponse.soap_get(soap, "afip3:FEParamGetTiposMonedasResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposIva(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposIva *afip3__FEParamGetTiposIva)
{
	struct __afip4__FEParamGetTiposIva soap_tmp___afip4__FEParamGetTiposIva;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposIva";
	soap_tmp___afip4__FEParamGetTiposIva.afip3__FEParamGetTiposIva = afip3__FEParamGetTiposIva;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FEParamGetTiposIva(soap, &soap_tmp___afip4__FEParamGetTiposIva);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FEParamGetTiposIva(soap, &soap_tmp___afip4__FEParamGetTiposIva, "-afip4:FEParamGetTiposIva", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FEParamGetTiposIva(soap, &soap_tmp___afip4__FEParamGetTiposIva, "-afip4:FEParamGetTiposIva", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposIva(_afip3__FEParamGetTiposIvaResponse &afip3__FEParamGetTiposIvaResponse)
{
	afip3__FEParamGetTiposIvaResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposIvaResponse.soap_get(soap, "afip3:FEParamGetTiposIvaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposOpcional(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposOpcional *afip3__FEParamGetTiposOpcional)
{
	struct __afip4__FEParamGetTiposOpcional soap_tmp___afip4__FEParamGetTiposOpcional;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposOpcional";
	soap_tmp___afip4__FEParamGetTiposOpcional.afip3__FEParamGetTiposOpcional = afip3__FEParamGetTiposOpcional;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FEParamGetTiposOpcional(soap, &soap_tmp___afip4__FEParamGetTiposOpcional);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FEParamGetTiposOpcional(soap, &soap_tmp___afip4__FEParamGetTiposOpcional, "-afip4:FEParamGetTiposOpcional", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FEParamGetTiposOpcional(soap, &soap_tmp___afip4__FEParamGetTiposOpcional, "-afip4:FEParamGetTiposOpcional", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposOpcional(_afip3__FEParamGetTiposOpcionalResponse &afip3__FEParamGetTiposOpcionalResponse)
{
	afip3__FEParamGetTiposOpcionalResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposOpcionalResponse.soap_get(soap, "afip3:FEParamGetTiposOpcionalResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposConcepto(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposConcepto *afip3__FEParamGetTiposConcepto)
{
	struct __afip4__FEParamGetTiposConcepto soap_tmp___afip4__FEParamGetTiposConcepto;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposConcepto";
	soap_tmp___afip4__FEParamGetTiposConcepto.afip3__FEParamGetTiposConcepto = afip3__FEParamGetTiposConcepto;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FEParamGetTiposConcepto(soap, &soap_tmp___afip4__FEParamGetTiposConcepto);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FEParamGetTiposConcepto(soap, &soap_tmp___afip4__FEParamGetTiposConcepto, "-afip4:FEParamGetTiposConcepto", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FEParamGetTiposConcepto(soap, &soap_tmp___afip4__FEParamGetTiposConcepto, "-afip4:FEParamGetTiposConcepto", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposConcepto(_afip3__FEParamGetTiposConceptoResponse &afip3__FEParamGetTiposConceptoResponse)
{
	afip3__FEParamGetTiposConceptoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposConceptoResponse.soap_get(soap, "afip3:FEParamGetTiposConceptoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetPtosVenta(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetPtosVenta *afip3__FEParamGetPtosVenta)
{
	struct __afip4__FEParamGetPtosVenta soap_tmp___afip4__FEParamGetPtosVenta;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetPtosVenta";
	soap_tmp___afip4__FEParamGetPtosVenta.afip3__FEParamGetPtosVenta = afip3__FEParamGetPtosVenta;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FEParamGetPtosVenta(soap, &soap_tmp___afip4__FEParamGetPtosVenta);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FEParamGetPtosVenta(soap, &soap_tmp___afip4__FEParamGetPtosVenta, "-afip4:FEParamGetPtosVenta", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FEParamGetPtosVenta(soap, &soap_tmp___afip4__FEParamGetPtosVenta, "-afip4:FEParamGetPtosVenta", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetPtosVenta(_afip3__FEParamGetPtosVentaResponse &afip3__FEParamGetPtosVentaResponse)
{
	afip3__FEParamGetPtosVentaResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetPtosVentaResponse.soap_get(soap, "afip3:FEParamGetPtosVentaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposCbte(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposCbte *afip3__FEParamGetTiposCbte)
{
	struct __afip4__FEParamGetTiposCbte soap_tmp___afip4__FEParamGetTiposCbte;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposCbte";
	soap_tmp___afip4__FEParamGetTiposCbte.afip3__FEParamGetTiposCbte = afip3__FEParamGetTiposCbte;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FEParamGetTiposCbte(soap, &soap_tmp___afip4__FEParamGetTiposCbte);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FEParamGetTiposCbte(soap, &soap_tmp___afip4__FEParamGetTiposCbte, "-afip4:FEParamGetTiposCbte", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FEParamGetTiposCbte(soap, &soap_tmp___afip4__FEParamGetTiposCbte, "-afip4:FEParamGetTiposCbte", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposCbte(_afip3__FEParamGetTiposCbteResponse &afip3__FEParamGetTiposCbteResponse)
{
	afip3__FEParamGetTiposCbteResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposCbteResponse.soap_get(soap, "afip3:FEParamGetTiposCbteResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposDoc(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposDoc *afip3__FEParamGetTiposDoc)
{
	struct __afip4__FEParamGetTiposDoc soap_tmp___afip4__FEParamGetTiposDoc;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposDoc";
	soap_tmp___afip4__FEParamGetTiposDoc.afip3__FEParamGetTiposDoc = afip3__FEParamGetTiposDoc;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FEParamGetTiposDoc(soap, &soap_tmp___afip4__FEParamGetTiposDoc);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FEParamGetTiposDoc(soap, &soap_tmp___afip4__FEParamGetTiposDoc, "-afip4:FEParamGetTiposDoc", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FEParamGetTiposDoc(soap, &soap_tmp___afip4__FEParamGetTiposDoc, "-afip4:FEParamGetTiposDoc", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposDoc(_afip3__FEParamGetTiposDocResponse &afip3__FEParamGetTiposDocResponse)
{
	afip3__FEParamGetTiposDocResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposDocResponse.soap_get(soap, "afip3:FEParamGetTiposDocResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapProxy::send_FEParamGetTiposPaises(const char *soap_endpoint_url, const char *soap_action, _afip3__FEParamGetTiposPaises *afip3__FEParamGetTiposPaises)
{
	struct __afip4__FEParamGetTiposPaises soap_tmp___afip4__FEParamGetTiposPaises;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
	if (soap_action == NULL)
		soap_action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposPaises";
	soap_tmp___afip4__FEParamGetTiposPaises.afip3__FEParamGetTiposPaises = afip3__FEParamGetTiposPaises;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___afip4__FEParamGetTiposPaises(soap, &soap_tmp___afip4__FEParamGetTiposPaises);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___afip4__FEParamGetTiposPaises(soap, &soap_tmp___afip4__FEParamGetTiposPaises, "-afip4:FEParamGetTiposPaises", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___afip4__FEParamGetTiposPaises(soap, &soap_tmp___afip4__FEParamGetTiposPaises, "-afip4:FEParamGetTiposPaises", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int ServiceSoapProxy::recv_FEParamGetTiposPaises(_afip3__FEParamGetTiposPaisesResponse &afip3__FEParamGetTiposPaisesResponse)
{
	afip3__FEParamGetTiposPaisesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	afip3__FEParamGetTiposPaisesResponse.soap_get(soap, "afip3:FEParamGetTiposPaisesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
